import json
from sys import platform
import requests


currentBeta = ["cupid","zeus","daumier","mayfly","unicorn","thor","fuxi","fuxi","nuwa","nuwa","ishtar","zizhan","babylon","dagu","rubens","matisse","ingres","diting","mondrian","socrates"]
currentStable = ["umi","cmi","monet","vangogh","cas","thyme","venus","courbet","star","renoir","agate","vili","lisa","pissarroin","cupid","zeus","psyche","daumier","mayfly","unicorn","thor","taoyao","plato","fuxi","nuwa","ishtar","cetus","odin","zizhan","babylon","nabu","elish","enuma","dagu","pipa","liuqin","yudi","mona","zijin","ziyi","yuechu","lancelot","dandelion","angelica","angelican","cattail","dandelion_c3l2","fog","fire","earth","biloba","merlin","lime","cannon","gauguin","joyeuse","excalibur","curtana","mojito","curtana_in_rf","sweet","camellia","chopin","rosemary","lilac","selene","evergo","pissarro","spes","spesn","veux","fleur","viva","vida","light","lightcm","opal","xaga","sunstone","sky","ruby","redwood","marble","pearl","tapas","topaz","sweet_k6a","sea","gold","garnet","zircon","cezanne","apollo","alioth","haydn","ares","munch","ingres","rubens","matisse","diting","mondrian","socrates","corot","rembrandt","yunluo","xun","ice","water","angelicain","frost","evergreen","rock","rosemary_p","surya","vayu","moonstone"]
newDevices = ["duchamp","sapphiren","sapphire","aurora","manet","vermeer","aristotle","houji","shennong","garnet","zircon","gold",]
fullDevices = ["aether","agate","alioth","aliothin","amber","andromeda","angelica","angelicain","angelican","apollo","aqua","ares","aresin","aries","aristotle","armani","atom","aurora","babylon","begonia","beryllium","bhima","biloba","bomb","cactus","camellia","camellian","cancro_lte_ct","cancro","cannon","cannong","cappu","capricorn","cas","cattail","cepheus","cereus","cetus","cezanne","chiron","chopin","citrus","cloud","clover","cmi","corot","courbet","crux","cupid","curtana_in_rf","curtana","dagu","daisy","dandelion_c3l2","dandelion","daumier","davinci","dior","dipper","diting","draco","duchamp","earth","elish","enuma","eos","equuleus","evergo","evergreen","excalibur","ferrari","fire","fleur","fog","frost","fuxi","galahad","garnet","gauguin","gauguininpro","gauguinpro","gemini","ginkgo","gold","gram","grus","gucci","haydn","haydnin","heat","helium","hennessy","hermes","HM2013023","HM2014011","HM2014501","houji","hydrogen","ice","ido_xhdpi","ido","ingres","iris","ishtar","jasmine","jason","joyeuse","karna","kate","kenzo","lancelot","land","latte","laurel_sprout","laurel","laurus","lavender","lcsh92_wet_jb9","lcsh92_wet_tdd","lcsh92_wet_xm_td","lcsh92","lemon","leo","libra","light","lightcm","lilac","lime","lisa","lithium","liuqin","lmi","lmipro","lotus","lte26007","maltose","manet","marble","markw","matisse","mayfly","meri","merlin","merlinnfc","mido","miel","mione_plus","mione","mocha","mojito","mona","mondrian","monet","moonstone","munch","nabu","natrium","nikel","nitrogen","nuwa","ocean","odin","olive","olivelite","olivewood","omega","onc","onclite","opal","oxygen","pearl","perseus","peux","phoenix","picasso_48m","picasso","pine","pipa","pisces","pissarro","pissarroin","pissarroinpro","pissarropro","platina","plato","polaris","pomelo","prada","psyche","pyxis","rain","raphael","raphaels","redwood","rembrandt","renoir","riva","river","rock","rolex","rosemary_p","rosemary","rosy","rubens","ruby","rubyplus","rubypro","sagit","sakura","santoni","sapphire","sapphiren","scorpio","sea","secret","selene","shennong","shiva","sirius","sky","snow","socrates","spes","spesn","star","sunstone","surya","sweet_k6a","sweet","taoyao","tapas","taurus","thor","thunder","thyme","tiare","tiffany","tissot","toco","topaz","tucana","tulip","ugg","ugglite","umi","unicorn","ursa","vangogh","vayu","vela","venus","vermeer","veux","vida","vili","vince","violet","virgo_lte_ct","virgo","viva","water","wayne","whyred","willow","wind","wt86047_pro","wt86047","wt88047_pro","wt88047","wt93007","wt93807","wt96007","wt98007","xaga","xagain","xagapro","xun","ysl","yudi","yuechu","yunluo","zeus","zijin","zircon","ziyi","zizhan"]
CurrentIDS = ["1900587","1900586","1900585","1900584","1900583","1900582","1900581","1900580","1900579","1900578","1900577","1900576","1900575","1900574","1900573","1900571","1900570","1900567","1900566","1900565","1900564","1900563","1900562","1900561","1900560","1900559","1900558","1900557","1900556","1900555","1900554","1900553","1900552","1900551","1900549","1900547","1900546","1900545","1900544","1900543","1900539","1900538","1900536","1900535","1900534","1900533","1900532","1900531","1900530","1900529","1900454","1900453","1900458","1900457","1900456","1900455","1900452","1900450","1900449","1900448","1900447","1900446","1900445","1900440","1900439","1900438","1900436","1900435","1900431","1900430","1900429","1900428","1900427","1900425","1900423","1900440","1900439","1900438","1900436","1900435","1900431","1900430","1900429","1900428","1900427","1900425","1900423","1900422","1900420","1900419","1900418","1900415","1900413","1900412","1900411","1900410","1900409","1900408","1900407","1900406","1900405","1900404","1900403","1900401","1900400","1900399","1900398","1900397","1900396","1900395","1900394","1900393","1900392","1900391","1900390","1900389","1900387","1900386","1900385","1900383","1900382","1900381","1900380","1900379","1900378","1900377","1900376","1900375","1900374","1900372","1900369","1700360"]
Full = ["1900587","1900586","1900585","1900584","1900583","1900582","1900581","1900580","1900579","1900578","1900577","1900576","1900575","1900574","1900573","1900571","1900570","1900567","1900566","1900565","1900564","1900563","1900562","1900561","1900560","1900559","1900558","1900557","1900556","1900555","1900554","1900553","1900552","1900551","1900549","1900547","1900546","1900545","1900544","1900543","1900539","1900538","1900536","1900535","1900534","1900533","1900532","1900531","1900530","1900529","1900528","1900527","1900526","1900525","1900458","1900457","1900456","1900455","1900454","1900453","1900452","1900450","1900449","1900448","1900447","1900446","1900445","1900440","1900439","1900438","1900436","1900435","1900431","1900430","1900429","1900428","1900427","1900425","1900423","1900422","1900420","1900419","1900418","1900415","1900413","1900412","1900411","1900410","1900409","1900408","1900407","1900406","1900405","1900404","1900403","1900401","1900400","1900399","1900398","1900397","1900396","1900395","1900394","1900393","1900392","1900391","1900390","1900389","1900387","1900386","1900385","1900383","1900382","1900381","1900380","1900379","1900378","1900377","1900376","1900375","1900374","1900373","1900372","1900371","1900370","1900369","1900367","1900366","1900365","1900362","1900361","1900360","1900357","1900356","1900355","1900354","1900353","1900351","1900346","1900343","1900342","1900341","1900340","1900338","1900336","1900334","1900333","1900332","1900328","1900326","1900323","1900321","1900320","1900319","1900318","1900317","1900316","1900315","1900314","1900309","1900303","1900302","1900301","1900299","1900298","1900297","1900274","1900261","1900240","1900101","1900082","1900037","1900001","1800367","1800366","1800365","1800362","1800361","1800360","1800357","1800356","1800355","1800354","1800353","1800351","1800346","1800343","1800342","1800341","1800340","1800338","1800336","1800334","1800333","1800332","1800328","1800326","1800323","1800321","1800320","1800319","1800318","1800317","1800316","1800315","1800314","1800309","1800303","1800302","1800301","1800299","1800298","1800297","1800274","1800261","1800240","1800101","1800082","1800037","1800001","1700367","1700366","1700365","1700362","1700361","1700360","1700357","1700356","1700355","1700354","1700353","1700351","1700349","1700346","1700345","1700343","1700342","1700341","1700340","1700338","1700336","1700334","1700333","1700332","1700328","1700326","1700323","1700321","1700320","1700319","1700318","1700317","1700316","1700315","1700314","1700309","1700303","1700302","1700301","1700299","1700298","1700297","1700274","1700261","1700240","1700101","1700082","1700037","1700002","1700001"]
flags = {"BL18.0": "mione_plus","BL15.0": "mione_plus","BH14.0": "mione_plus","NBF7.0": "mione_plus","NBD4.0": "mione_plus","NAH1.0": "mione_plus","CS23.0": "mione_plus","CS21.0": "mione_plus","CS19.0": "mione_plus","CS16.0": "mione_plus","CS15.0": "mione_plus","CS14.0": "mione_plus","CS13.0": "mione_plus","ICS7.0": "mione_plus","ICS6.0": "mione_plus","ICS5.0": "mione_plus","ICS3.0": "mione_plus","ICS2.0": "mione_plus","ICS1.0": "mione_plus","CS24.0": "mione_plus","CS22.0": "mione_plus","CS20.0": "mione_plus",
    "XACNEK": "aries","XACNED": "aries","XACNDL": "aries","XACNDI": "aries","XACNDG": "aries","XACNDE": "aries","XACNDD": "aries","XACNDA": "aries","XACNDB": "aries","XACNCK": "aries","XACNCI": "aries","XACNCH": "aries","XACNCF": "aries","XACNCD": "aries","LB53.0": "aries","JLB3.0": "aries","LB22.2": "aries","LB20.0": "aries","LB16.0": "aries","LB30.0": "aries","XAMIEK": "aries","XAMIED": "aries","XAMIDI": "aries","XAMIDG": "aries","XAMIDE": "aries","XAMIDA": "aries","XAMICK": "aries","XAMICH": "aries","XAMICF": "aries","LB55.0": "aries","LB48.0": "aries","LB42.0": "aries","LB40.0": "aries",
    "LB54.0": "taurus","LB52.0": "taurus","LB50.0": "taurus","LB49.0": "taurus","LB39.0": "taurus","LB36.0": "taurus","LB34.0": "taurus","LB33.0": "taurus","LB29.0": "taurus","LB28.0": "taurus","LB27.0": "taurus","LB24.0": "taurus","LB23.0": "taurus","LB22.0": "taurus","LB21.0": "taurus","LB18.0": "taurus","LB17.0": "taurus","LB15.0": "taurus","LB14.0": "taurus",
    "XCCNEK": "pisces","XCCNED": "pisces","XCCNDL": "pisces","XCCNDI": "pisces","XCCNDG": "pisces","XCCNDE": "pisces","XCCNDD": "pisces","XCCNDA": "pisces","XCCNCK": "pisces","XCCNCI": "pisces","XCCNCH": "pisces","XCCNCF": "pisces","XCCNCD": "pisces","XCCNCB": "pisces","XCCNBL": "pisces","XCCNBK": "pisces","XCCNBJ": "pisces","BH31.0": "pisces","BA13.0": "pisces","AL12.0": "pisces","AL11.0": "pisces","AL10.0": "pisces","NAI7.0": "pisces","NAI6.0": "pisces","NAI3.5": "pisces","NAI3.4": "pisces","BF25.0": "pisces","BE21.0": "pisces","BD20.0": "pisces","BD19.0": "pisces",
    "XDCNFD": "cancro","XDCNFA": "cancro","XDCNEK": "cancro","XDCNED": "cancro","XDCNDL": "cancro","XDCNDI": "cancro","XDCNDG": "cancro","XDCNDE": "cancro","XDCNDD": "cancro","XDCNDB": "cancro","XDCNCK": "cancro","XDCNCI": "cancro","XDCNCH": "cancro","XDCNCF": "cancro","XDCNCD": "cancro","XDCNCB": "cancro","XDCNBL": "cancro","XDCNBK": "cancro","XDCNBJ": "cancro","XDCNFI": "cancro","BF24.0": "cancro","BE17.0": "cancro","NBA9.0": "cancro","NBA8.0": "cancro","NAL4.0": "cancro","NAL2.0": "cancro","BF21.0": "cancro","KBA8.0": "cancro","KBA6.0": "cancro","WBA8.0": "cancro","WBA6.0": "cancro","BD13.0": "cancro","BA12.0": "cancro","BA10.0": "cancro","GBA8.0": "cancro","XDMIFA": "cancro","XDMIEK": "cancro","XDMIED": "cancro","XDMIDI": "cancro","XDMIDG": "cancro","XDMIDE": "cancro","XDMICK": "cancro","XDMICI": "cancro","XDMICH": "cancro","XDMICF": "cancro","XDMICD": "cancro","XDMICB": "cancro","XDMIBL": "cancro","BH34.0": "cancro","BH32.0": "cancro","BF23.0": "cancro","BF22.0": "cancro","BF19.0": "cancro","BE18.0": "cancro","BE15.0": "cancro",
    "XGCNFI": "cancro_lte_ct","XGCNFD": "cancro_lte_ct","XGCNFA": "cancro_lte_ct","XGCNEK": "cancro_lte_ct","XGCNED": "cancro_lte_ct","XGCNDL": "cancro_lte_ct","XGCNDI": "cancro_lte_ct","XGCNDG": "cancro_lte_ct","XGCNDE": "cancro_lte_ct","XGCNDD": "cancro_lte_ct","XGCNDB": "cancro_lte_ct","XGCNCK": "cancro_lte_ct","XGCNCI": "cancro_lte_ct","XGCNCH": "cancro_lte_ct","XGCNCF": "cancro_lte_ct","XGCNCD": "cancro_lte_ct","XGCNCB": "cancro_lte_ct","XGCNBL": "cancro_lte_ct",
    "XICNDE": "ferrari", "XICNDD": "ferrari", "XICNDA": "ferrari", "XICNCK": "ferrari", "XICNCI": "ferrari", "XICNCH": "ferrari", "XICNCF": "ferrari", "XICNCD": "ferrari", "XIMIEK": "ferrari", "XIMIED": "ferrari", "XIMIDI": "ferrari", "XIMIDG": "ferrari", "XIMIDE": "ferrari", "XIMIDD": "ferrari", "XIMIDA": "ferrari", "XIMICK": "ferrari", "XIMICI": "ferrari", "XIMICH": "ferrari", "XIMICF": "ferrari", "XIMICD": "ferrari",
    "XKCNFI": "libra", "XKCNFD": "libra", "XKCNFA": "libra", "XKCNEK": "libra", "XKCNEI": "libra", "XKCNED": "libra", "XKCNEC": "libra", "XKCNDL": "libra", "XKCNDI": "libra", "XKCNDG": "libra", "XKCNDE": "libra", "XKCNDD": "libra", "XKCNDA": "libra", "XKCNCK": "libra", "XKCNCI": "libra", "XKCNCF": "libra",
    "AJCNFI": "aqua","AJCNFD": "aqua","AJCNFA": "aqua","AJCNEK": "aqua","AJCNEI": "aqua","AJCNED": "aqua","AJCNDL": "aqua","AJCNDI": "aqua","AJCNDG": "aqua","AJCNDE": "aqua","AJCNDD": "aqua","AJCNDA": "aqua",
    "AACNXM": "gemini","AACNFH": "gemini","AACNFD": "gemini","AACNFA": "gemini","AACNEK": "gemini","AACNEI": "gemini","AACNED": "gemini","AACNEB": "gemini","AACNDI": "gemini","AACNDH": "gemini","AACNDE": "gemini","AACNDD": "gemini","AACNDB": "gemini","AAMIXM": "gemini","AAMIFH": "gemini","AAMIFD": "gemini","AAMIFA": "gemini","AAMIEK": "gemini","AAMIEI": "gemini","AAMIED": "gemini","AAMIEB": "gemini","AAMIDI": "gemini","AAMIDG": "gemini","AAMIDE": "gemini","AAMIDD": "gemini",
    "AGCNXM": "capricorn","AGCNFI": "capricorn","AGCNFD": "capricorn","AGCNFA": "capricorn","AGCNEK": "capricorn","AGCNEI": "capricorn","AGCNED": "capricorn","AGCNDL": "capricorn","AGCNDI": "capricorn","AGCNDH": "capricorn","AGMIXM": "capricorn","AGMIFI": "capricorn","AGMIFD": "capricorn","AGMIFA": "capricorn","AGMIEK": "capricorn","AGMIEI": "capricorn","AGMIED": "capricorn","AGMIDL": "capricorn","AGMIDI": "capricorn",
    "BGCNXM": "natrium","BGCNFI": "natrium","BGCNFD": "natrium","BGCNFA": "natrium","BGCNEK": "natrium","BGCNEI": "natrium","BGCNED": "natrium","BGCNDL": "natrium","BGCNDI": "natrium","BGCNDH": "natrium","BGMIXM": "natrium","BGMIFI": "natrium","BGMIFD": "natrium","BGMIFA": "natrium","BGMIEK": "natrium","BGMIEI": "natrium","BGMIED": "natrium","BGMIDL": "natrium","BGMIDI": "natrium","BGMIDG": "natrium",
    "CJCNXM": "meri","CJCNFI": "meri","CJCNFD": "meri","CJCNFA": "meri","CJCNEK": "meri","CJCNEI": "meri","CJCNED": "meri","CJCNDI": "meri",
    "DBCNXM": "tiffany","DBCNFI": "tiffany","DBCNFD": "tiffany","DBCNFA": "tiffany","DBCNEK": "tiffany","DBCNEI": "tiffany","DBCNED": "tiffany",
    "CACNXM": "sagit","CACNFK": "sagit","CACNFH": "sagit","CACNFD": "sagit","CACNFA": "sagit","CACNEK": "sagit","CACNEI": "sagit","CACNEG": "sagit","CACNEC": "sagit","CAMIXM": "sagit","CAMIFH": "sagit","CAMIFA": "sagit","CAMIEK": "sagit","CAMIEI": "sagit","CAMIEG": "sagit","CAMIEC": "sagit",
    "DCCNXM": "wayne","DCCNFH": "wayne","DCCNFD": "wayne","DCCNFA": "wayne",
    "EACNFI": "dipper","EACNFH": "dipper","EACNFD": "dipper","EACNFA": "dipper","EACNXM": "dipper","EAMIXM": "dipper","EAMIFI": "dipper","EAMIFH": "dipper","EAMIFD": "dipper","EAMIFA": "dipper","EARUXM": "dipper","EARUFH": "dipper","EARUFA": "dipper",
    "ECCNXM": "equuleus","ECCNFK": "equuleus","ECCNFH": "equuleus","ECCNFD": "equuleus","ECMIXM": "equuleus","ECMIFH": "equuleus","ECMIFD": "equuleus","ECRUXM": "equuleus",
    "EHCNXM": "ursa","EHCNFI": "ursa","EHCNFH": "ursa","EHCNFD": "ursa",
    "DTCNXM": "platina","DTCNFH": "platina","DTCNFD": "platina","DTMIXM": "platina","DTMIFH": "platina","DTMIFD": "platina","DTRUXM": "platina","DTRUFH": "platina","DTRUFD": "platina",
    "FACNXM": "cepheus","FAMIXM": "cepheus","FAEUXM": "cepheus","FARUXM": "cepheus","FALMCR": "cepheus","FAEUHG": "cepheus","FAMXTC": "cepheus",
    "FXCNXM": "crux",
    "JBCNXM": "umi","JBMIXM": "umi","JBEUXM": "umi","JBRUXM": "umi","JBINXM": "umi","JBIDXM": "umi","JBTRXM": "umi",
    "JACNXM": "cmi","JAMIXM": "cmi","JAEUXM": "cmi","JITWXM": "monet","JIMIXM": "monet","JIEUXM": "monet","JIJPKD": "monet","JIKRGU": "monet","JIKRKT": "monet","JIKRSK": "monet",
    "JVCNXM": "vangogh",
    "JJCNXM": "cas","KBCNXM": "venus","KBTWXM": "venus","KBMIXM": "venus","KBEUXM": "venus","KBRUXM": "venus","KBIDXM": "venus","KBTRXM": "venus","KBMXTC": "venus",
    "KKCNXM": "haydn","KKMIXM": "haydn","KKEUXM": "haydn","KKINXM": "haydn",
    "GACNDM": "thyme","GACNXM": "thyme",
    "KQMIXM": "courbet","KQEUXM": "courbet","KQRUXM": "courbet","KQINXM": "courbet","KQIDXM": "courbet","KQTRXM": "courbet","KQLMCR": "courbet","KQMXTC": "courbet",
    "Y01.K1":"star","KACNXM": "star","KAMIXM": "star","KAEUXM": "star","KAINXM": "star","KAIDXM": "star",
    ".YY.K9":"renoir","KICNXM": "renoir","KITWXM": "renoir","KIMIXM": "renoir","KIEUXM": "renoir","KIRUXM": "renoir","KILMCR": "renoir","KIMXTC": "renoir","KICLEN": "renoir","KIJPXM": "renoir",
    "KWTWXM": "agate","KWMIXM": "agate","KWEUXM": "agate","KWRUXM": "agate","KWIDXM": "agate","KWTRXM": "agate","KWCLEN": "agate","KWLMCR": "agate","KWMXAT": "agate",
    "KDTWXM": "vili","KDMIXM": "vili","KDEUXM": "vili","KDRUXM": "vili","KDINXM": "vili","KDIDXM": "vili","KDTRXM": "vili","KDJPXM": "vili","KDCLEN": "vili","KDMXAT": "vili","KDLMCR": "vili",
    "KOCNXM": "lisa","KOTWXM": "lisa","KOMIXM": "lisa","KOEUXM": "lisa","KORUXM": "lisa","KOINXM": "lisa","KOTRXM": "lisa","KOCLEN": "lisa","KOMXTC": "lisa","KOMXAT": "lisa","KOLMCR": "lisa",
    "KTINFK": "pissarroin",
    ".XY.L3":"cupid","LCCNXM": "cupid","LCTWXM": "cupid","LCMIXM": "cupid","LCEUXM": "cupid","LCRUXM": "cupid","LCIDXM": "cupid","LCTRXM": "cupid","LCLMCR": "cupid","LCMXAT": "cupid",
    "DEE.L2":"zeus",".XY.L2":"zeus","LBCNXM": "zeus","LBTWXM": "zeus","LBMIXM": "zeus","LBEUXM": "zeus","LBRUXM": "zeus","LBINXM": "zeus","LBIDXM": "zeus","LBTRXM": "zeus",
    "LDCNXM": "psyche","LDTWXM": "psyche","LDMIXM": "psyche","LDEUXM": "psyche","LDRUXM": "psyche",
    "LGCNXM": "daumier",
    "LTCNXM": "mayfly","LTCNDM":"mayfly",
    "LECNXM": "unicorn",
    "LACNXM": "thor",
    "LITWXM": "taoyao","LIMIXM": "taoyao","LIEUXM": "taoyao","LIRUXM": "taoyao","LIIDXM":"taoyao","LITRXM":"taoyao","LILMCR":"taoyao","LICLEN":"taoyao",
    "LQTWXM": "plato","LQMIXM": "plato","LQEUXM": "plato","LQRUXM": "plato","LQIDXM": "plato","LQTRXM": "plato","LQCLEN": "plato","LQLMCR": "plato",
    "DEE.M3":"fuxi","MCCNXM": "fuxi","MCTWXM": "fuxi","MCMIXM": "fuxi","MCEUXM": "fuxi","MCRUXM": "fuxi","MCTRXM":"fuxi",
    "DEE.M2":"nuwa","MBCNXM": "nuwa","MBTWXM": "nuwa","MBMIXM": "nuwa","MBEUXM": "nuwa","MBRUXM": "nuwa","MBTRXM": "nuwa","MBINXM":"nuwa",
    "EBCNXM": "sirius","EBCNFK": "sirius","EBCNFH": "sirius","EBCNFA": "sirius",
    "FBCNXM": "grus","FBMIXM": "grus","FBEUXM": "grus","FBRUXM": "grus",
    "FCCNXM": "pyxis","FCMIXM": "pyxis","FCEUXM": "pyxis","FCRUXM": "pyxis",
    "FECNXM": "vela",
    "FMCNXM": "laurus",
    "FDCNXM": "tucana","FDMIXM": "tucana","FDEUXM": "tucana","FDRUXM": "tucana","FDIDXM": "tucana","FDMXTC": "tucana",
    "XECNEK": "virgo","XECNED": "virgo","XECNDL": "virgo","XECNDI": "virgo","XECNDG": "virgo","XECNDE": "virgo","XECNDD": "virgo","XECNDB": "virgo","XECNCK": "virgo","XECNCI": "virgo","XECNCH": "virgo","XECNCF": "virgo","XECNCD": "virgo","XECNCB": "virgo","XECNBL": "virgo","XEMIFA": "virgo","XEMIEK": "virgo","XEMIDL": "virgo","XEMIDI": "virgo","XEMIDG": "virgo","XEMIDE": "virgo","XEMICK": "virgo","XEMICI": "virgo","XEMICH": "virgo","XEMICF": "virgo",
    "XJCNCK": "virgo_lte_ct","XJCNCI": "virgo_lte_ct","XJCNCH": "virgo_lte_ct","XJCNCF": "virgo_lte_ct","XJCNCD": "virgo_lte_ct",
    "XHCNEK": "leo","XHCNEI": "leo","XHCNED": "leo","XHCNEC": "leo","XHCNDL": "leo","XHCNDI": "leo","XHCNDG": "leo","XHCNDE": "leo","XHCNDD": "leo","XHCNDA": "leo","XHCNCK": "leo","XHCNCI": "leo","XHCNCH": "leo","XHCNCF": "leo","XHCNCD": "leo",
    "ADCNXM": "scorpio","ADCNFK": "scorpio","ADCNFH": "scorpio","ADCNFD": "scorpio","ADCNFA": "scorpio","ADCNEK": "scorpio","ADCNEI": "scorpio","ADCNED": "scorpio","ADCNDL": "scorpio","ADCNDI": "scorpio","ADMIXM": "scorpio","ADMIFH": "scorpio","ADMIFD": "scorpio","ADMIFA": "scorpio","ADMIEK": "scorpio","ADMIED": "scorpio","ADMIDL": "scorpio",
    "CHCNXM": "jason","CHCNFK": "jason","CHCNFH": "jason","CHCNFD": "jason","CHCNFA": "jason","CHCNEK": "jason","CHCNEI": "jason","CHCNED": "jason","CHMIXM": "jason","CHMIFI": "jason","CHMIFD": "jason","CHMIFA": "jason","CHMIEI": "jason",
    "FNMIXM": "toco","FNEUXM": "toco","FNRUXM": "toco","FNTRXM": "toco",
    "BCCNXM": "hydrogen","BCCNFK": "hydrogen","BCCNFI": "hydrogen","BCCNFD": "hydrogen","BCCNFA": "hydrogen","BCCNEK": "hydrogen","BCCNEI": "hydrogen","BCCNED": "hydrogen","BCCNDL": "hydrogen","BCCNDI": "hydrogen","BCCNDG": "hydrogen","BCCNDE": "hydrogen","BCCNDC": "hydrogen","BCMIXM": "hydrogen","BCMIFI": "hydrogen","BCMIFD": "hydrogen","BCMIFA": "hydrogen","BCMIEK": "hydrogen","BCMIEI": "hydrogen","BCMIED": "hydrogen","BCMIDL": "hydrogen","BCMIDI": "hydrogen","BCMIDG": "hydrogen","BCMIDE": "hydrogen",
    "BDCNXM": "helium","BDCNFI": "helium","BDCNFD": "helium","BDCNFA": "helium","BDCNEK": "helium","BDCNEI": "helium","BDCNED": "helium","BDCNDL": "helium","BDCNDI": "helium","BDCNDG": "helium","BDCNDE": "helium","BDMIXM": "helium","BDMIFI": "helium","BDMIFD": "helium","BDMIFA": "helium","BDMIEK": "helium","BDMIEI": "helium","BDMIED": "helium","BDMIDL": "helium","BDMIDI": "helium","BDMIDG": "helium",
    "DDCNXM": "oxygen","DDCNFI": "oxygen","DDCNFD": "oxygen","DDCNFA": "oxygen","DDCNEK": "oxygen","DDCNEI": "oxygen","DDCNED": "oxygen","DDMIXM": "oxygen","DDMIFD": "oxygen","DDMIFA": "oxygen","DDMIEK": "oxygen","DDMIEI": "oxygen","DDMIED": "oxygen",
    "EDCNXM": "nitrogen","EDCNFH": "nitrogen","EDCNFD": "nitrogen","EDMIXM": "nitrogen","EDMIFK": "nitrogen","EDMIFH": "nitrogen","EDMIFD": "nitrogen","EDRUXM": "nitrogen","EDRUFH": "nitrogen","EDRUFD": "nitrogen",
    "AHCNXM": "lithium","AHCNFK": "lithium","AHCNFH": "lithium","AHCNFD": "lithium","AHCNFA": "lithium","AHCNEK": "lithium","AHCNEI": "lithium","AHCNED": "lithium","AHCNDL": "lithium","AHCNDI": "lithium","AHMIXM": "lithium","AHMIFH": "lithium","AHMIFD": "lithium","AHMIFA": "lithium","AHMIEK": "lithium","AHMIEI": "lithium","AHMIED": "lithium","AHMIDL": "lithium",
    "DECNXM": "chiron","DECNFH": "chiron","DECNFD": "chiron","DECNFA": "chiron","DECNEK": "chiron","DECNEF": "chiron","DEMIXM": "chiron","DEMIFH": "chiron","DEMIFD": "chiron","DEMIFA": "chiron","DEMIEK": "chiron","DEMIEI": "chiron","DEMIEF": "chiron",
    "DGCNXM": "polaris","DGCNFH": "polaris","DGCNFD": "polaris","DGCNFA": "polaris","DGMIXM": "polaris","DGMIFH": "polaris","DGMIFD": "polaris","DGMIFA": "polaris","DGRUXM": "polaris","DGRUFA": "polaris","EECNXM": "perseus","EECNFH": "perseus","EEMIXM": "perseus","EEMIFH": "perseus","EEMIHG": "perseus","EERUXM": "perseus","EERUFH": "perseus",
    "EMCNXM": "andromeda","EMMIXM": "andromeda","EMEUXM": "andromeda",
    "JTCNXM": "cetus",
    "KMCNXM": "odin",
    "LRCNXM": "zizhan",
    "XFCNEK": "mocha","XFCNED": "mocha","XFCNDL": "mocha","XFCNDI": "mocha","XFCNDE": "mocha","XFCNDD": "mocha","XFCNDA": "mocha","XFCNCK": "mocha","XFCNCI": "mocha","XFCNCH": "mocha","XFCNCF": "mocha","XFCNCD": "mocha","XFCNCB": "mocha","XFCNBL": "mocha","XFCNBK": "mocha","XFCNBJ": "mocha","BH11.0": "mocha","NBH9.0": "mocha","NBF5.0": "mocha","NBF4.0": "mocha","NBF2.0": "mocha","XFMIDE": "mocha","XFMIDD": "mocha","XFMIDA": "mocha","XFMICK": "mocha","XFMICI": "mocha","XFMICH": "mocha","XFMICF": "mocha","XFMICD": "mocha","XFMICB": "mocha","XFMIBL": "mocha",
    "ACCNFD": "latte","ACCNFA": "latte","ACCNEK": "latte","ACCNED": "latte","ACCNDL": "latte","ACCNDI": "latte","ACCNDE": "latte","ACCNDA": "latte","ACCNCL": "latte","ACCNCK": "latte","XLCNCK": "latte","XLCNCJ": "latte",
    "CICNXM": "cappu","CICNFI": "cappu","CICNFD": "cappu","CICNFA": "cappu","CICNEK": "cappu","CICNEG": "cappu","CICNEB": "cappu",
    "DJCNXM": "clover","DJCNFI": "clover","DJCNFD": "clover",
    "EE.K82":"nabu","KXCNXM": "nabu","KXCNDM": "nabu","KXTWXM": "nabu","KXMIXM": "nabu","KXEUXM": "nabu","KXRUXM": "nabu","KXINXM": "nabu","KXTRXM": "nabu",
    "E.K81A":"elish","KYCNXM": "elish",
    "KJ.K81":"enuma","KZCNXM": "enuma","KZCNDM": "enuma",
    "LZCNXM": "dagu",
    "KVCNXM": "mona",
    "LPCNXM": "zijin",
    "LLCNXM": "ziyi","LLTWXM": "ziyi","LLMIXM": "ziyi","LLEUXM": "ziyi","LLRUXM": "ziyi","LLTRXM": "ziyi",
    "DHMIXM": "tissot","DHMIFA": "tissot","DHMIFE": "tissot",
    "DIMIXM": "jasmine","DIMIFJ": "jasmine","DIMIFE": "jasmine",
    "DLMIXM": "daisy","DLMIFJ": "daisy","DLMIFF": "daisy",
    "FQMIXM": "laurel","FQEUXM": "laurel",
    "FICNXM": "lotus","FICNFI": "lotus","FIMIXM": "lotus","FIRUXM": "lotus",
    "HBCNDD": "wt98007","HBMICF": "wt98007",
    "HCCNEK": "armani","HCCNED": "armani","HCCNDL": "armani","HCCNDI": "armani","HCCNDG": "armani","HCCNDE": "armani","HCCNDD": "armani","HCCNDA": "armani","HCCNCK": "armani","HCCNCI": "armani","HCCNCH": "armani","HCCNCF": "armani","HCMIEK": "armani","HCMIDL": "armani","HCMIDI": "armani","HCMIDG": "armani","HCMIDE": "armani","HCMIDD": "armani","HCMIDA": "armani","HCMICK": "armani","HCMICI": "armani","HCMICH": "armani","HCMICF": "armani",
    "HFCNEK": "wt93807","HFCNED": "wt93807","HFCNDL": "wt93807","HFCNDI": "wt93807","HFCNDG": "wt93807","HFCNDE": "wt93807","HFCNDA": "wt93807","HFCNCK": "wt93807","BL28.0": "wt93807","BL27.0": "wt93807","BH24.0": "wt93807","BF18.0": "wt93807","BF17.0": "wt93807","NBC6.0": "wt93807","NBC4.0": "wt93807",
    "HHCNEK": "wt96007","HHCNED": "wt96007","HHCNDL": "wt96007","HHCNDI": "wt96007","HHCNDG": "wt96007","HHCNDE": "wt96007","HHCNDD": "wt96007","HHCNDA": "wt96007","HHCNCK": "wt96007","HHCNCI": "wt96007","HHCNCF": "wt96007",
    "HJCNDA": "wt88047","HJCNCK": "wt88047","HJCNCI": "wt88047","HJCNCH": "wt88047","HJCNCF": "wt88047","HJCNCD": "wt88047","HJCNCB": "wt88047","HJCNBL": "wt88047","HJCNBK": "wt88047","HJMIDL": "wt88047","HJMIDD": "wt88047","HJMIDA": "wt88047","HJMICK": "wt88047","HJMICI": "wt88047","HJMICH": "wt88047","HJMICF": "wt88047","HJMICD": "wt88047","HJMICB": "wt88047","HJMIBL": "wt88047","HJMIBK": "wt88047",
    "HJCNEK": "wt88047_pro","HJCNED": "wt88047_pro","HJCNDL": "wt88047_pro","HJCNDI": "wt88047_pro","HJCNDG": "wt88047_pro","HJCNDE": "wt88047_pro","HJCNDD": "wt88047_pro","HJMIEK": "wt88047_pro","HJMIED": "wt88047_pro","HJMIDI": "wt88047_pro","HJMIDG": "wt88047_pro","HJMIDE": "wt88047_pro",
    "HLCNEK": "lte26007","HLCNED": "lte26007","HLCNDL": "lte26007","HLCNDI": "lte26007","HLCNDG": "lte26007","HLCNDE": "lte26007","HLCNDD": "lte26007","HLCNDB": "lte26007","HLCNCK": "lte26007","HLCNCI": "lte26007","HLCNCH": "lte26007","HLCNCF": "lte26007","HLCNCD": "lte26007","HLCNCB": "lte26007",
    "AICNFD": "ido_xhdpi","AICNFA": "ido_xhdpi","AICNEK": "ido_xhdpi","AICNED": "ido_xhdpi","AICNDI": "ido_xhdpi","AICNDG": "ido_xhdpi","AICNDE": "ido_xhdpi","HPCNDD": "ido_xhdpi","HPCNDB": "ido_xhdpi","HPCNCK": "ido_xhdpi","AIMIFD": "ido_xhdpi","AIMIFA": "ido_xhdpi","AIMIEK": "ido_xhdpi","AIMIED": "ido_xhdpi","AIMIDL": "ido_xhdpi","AIMIDI": "ido_xhdpi","AIMIDG": "ido_xhdpi","AIMIDE": "ido_xhdpi",
    "ALCNXM": "land","ALCNFI": "land","ALCNFD": "land","ALCNFA": "land","ALCNEK": "land","ALCNED": "land","ALCNDI": "land","ALCNDG": "land","ALCNDE": "land","ALMIXM": "land","ALMIFI": "land","ALMIFD": "land","ALMIFA": "land","ALMIEK": "land","ALMIED": "land","ALMIDL": "land","ALMIDI": "land","ALMIDG": "land","ALMIDE": "land",
    "CECNXM": "prada","CECNFI": "prada","CECNFD": "prada","CECNFA": "prada","CECNEK": "prada","CECNED": "prada","CECNDI": "prada","CECNDG": "prada","CEMIXM": "prada","CEMIFI": "prada","CEMIFD": "prada","CEMIFA": "prada",
    "BECNXM": "markw","BECNFI": "markw","BECNFD": "markw","BECNFA": "markw","BECNEK": "markw","BECNED": "markw","BECNDL": "markw","BECNDI": "markw","BECNDG": "markw","BEMIXM": "markw","BEMIFI": "markw","BEMIFD": "markw","BEMIFA": "markw","BEMIEK": "markw","BEMIED": "markw","BEMIDL": "markw","BEMIDI": "markw",
    "CCCNXM": "rolex","CCCNFI": "rolex","CCCNFD": "rolex","CCCNFA": "rolex","CCCNEK": "rolex","CCCNED": "rolex","CCCNDL": "rolex","CCCNDI": "rolex","CCMIXM": "rolex","CCMIFI": "rolex","CCMIFD": "rolex","CCMIFA": "rolex","CCMIEK": "rolex","CCMIED": "rolex","CCMIDL": "rolex","CCMIDI": "rolex",
    "AMCNXM": "santoni","AMCNFI": "santoni","AMCNFD": "santoni","AMCNFA": "santoni","AMCNEK": "santoni","AMCNEI": "santoni","AMCNED": "santoni","AMCNEA": "santoni","AMMIXM": "santoni","AMMIFI": "santoni","AMMIFD": "santoni","AMMIFA": "santoni","AMMIEK": "santoni","AMMIEI": "santoni","AMMIED": "santoni","AMMIEA": "santoni",
    "DACNXM": "rosy","DACNFI": "rosy","DACNFD": "rosy","DACNFA": "rosy","DACNEK": "rosy","DACNEI": "rosy","DAMIXM": "rosy","DAMIFI": "rosy","DAMIFD": "rosy","DAMIFA": "rosy","DAMIEK": "rosy","DARUXM": "rosy","DARUFD": "rosy",
    "CKCNXM": "riva","CKCNFI": "riva","CKCNFD": "riva","CKCNFA": "riva","CKCNEK": "riva","CKCNEI": "riva","CKCNED": "riva","CKMIXM": "riva","CKMIFI": "riva","CKMIFD": "riva","CKMIFA": "riva","CKMIEK": "riva","CKMIEI": "riva",
    "EGCNXM": "vince","EGCNFK": "vince","EGCNFI": "vince","EGCNFD": "vince","EGCNFA": "vince","EGCNEK": "vince","EGCNEI": "vince","EGMIXM": "vince","EGMIFH": "vince","EGMIFD": "vince","EGMIFA": "vince","EGMIEK": "vince","EGRUFD": "vince","EGRUEK": "vince",
    "CGCNXM": "cereus","CGCNFH": "cereus","CGCNFD": "cereus","CGMIXM": "cereus","CGMIFH": "cereus","CGMIFD": "cereus","CGEUSF": "cereus","CGRUXM": "cereus","CGRUFD": "cereus","CBCNXM": "cactus","CBCNFH": "cactus","CBCNFD": "cactus","CBMIXM": "cactus","CBMIFH": "cactus","CBMIFD": "cactus","CBRUXM": "cactus","CBRUFD": "cactus",
    "DICNXM": "sakura","DICNFH": "sakura","DICNFD": "sakura","DMMIXM": "sakura","DMMIFH": "sakura","DMMIFD": "sakura",
    "FLCNXM": "onclite","FLMIXM": "onclite","FLEUXM": "onclite","FLRUXM": "onclite","FLINXM": "onclite","FLMXTC": "onclite","FLLMCR": "onclite",
    "CMCNXM": "pine","CMMIXM": "pine","CMEUXM": "pine","CMRUXM": "pine","CMINXM": "pine",
    "CNCNXM": "olive","CNMIXM": "olive","CNEUXM": "olive","CNRUXM": "olive","CNINXM": "olive","CNIDXM": "olive",
    "CPCNXM": "olivelite","CPMIXM": "olivelite","CPEUXM": "olivelite","CPRUXM": "olivelite","CPINXM": "olivelite","CPIDXM": "olivelite","CPMXTC": "olivelite","CPLMCR": "olivelite",
    "CQINXM": "olivewood","CQIDXM": "olivewood",
    "JHCNXM": "atom",
    "JLCNXM": "bomb",
    "JCCNXM": "lancelot","JCMIXM": "lancelot","JCEUXM": "lancelot","JCRUXM": "lancelot","JCINXM": "lancelot","JCIDXM": "lancelot","JCTRXM": "lancelot","JCCLEN": "lancelot","JCMXTC": "lancelot","JCMXAT": "lancelot","JCLMCR": "lancelot",
    "CDCNXM": "dandelion","CDMIXM": "dandelion","CDEUXM": "dandelion","CDRUXM": "dandelion","CDINXM": "dandelion","CDIDXM": "dandelion","CDTRXM": "dandelion","CDMXTC": "dandelion","CDMXAT": "dandelion","CDLMCR": "dandelion","CDZAMT": "dandelion",
    "CRMIXM": "angelica","CREUXM": "angelica","CRINXM": "angelica","CRIDXM": "angelica","CRTRXM": "angelica","CRMXTC": "angelica","CRMXAT": "angelica","CRLMCR": "angelica",
    "CSMIXM": "angelican","CSEUXM": "angelican","CSRUXM": "angelican",
    "CTINXM": "cattail",
    "CZCNXM": "dandelion_c3l2","CZTWXM": "dandelion_c3l2","CZMIXM": "dandelion_c3l2","CZEUXM": "dandelion_c3l2","CZRUXM": "dandelion_c3l2","CZINXM": "dandelion_c3l2","CZIDXM": "dandelion_c3l2","CZCLEN": "dandelion_c3l2","CZMXAT": "dandelion_c3l2","CZLMCR": "dandelion_c3l2","CZZAMT": "dandelion_c3l2",
    "GETWXM": "fog","GEMIXM": "fog","GEEUXM": "fog","GERUXM": "fog","GEINXM": "fog","GEIDXM": "fog","GETRXM": "fog","GECLEN": "fog","GEMXAT": "fog","GELMCR": "fog","GEZAMT": "fog",
    "HECNEK": "lcsh92_wet_xm_td","HECNED": "lcsh92_wet_xm_td","HECNDL": "lcsh92_wet_xm_td","HECNDI": "lcsh92_wet_xm_td","HECNDG": "lcsh92_wet_xm_td","HECNDE": "lcsh92_wet_xm_td","HECNDD": "lcsh92_wet_xm_td","HECNDA": "lcsh92_wet_xm_td","HECNCK": "lcsh92_wet_xm_td",
    "HDCNEK": "lcsh92_wet_jb9","HDCNED": "lcsh92_wet_jb9","HDCNDL": "lcsh92_wet_jb9","HDCNDG": "lcsh92_wet_jb9","HDCNDE": "lcsh92_wet_jb9","HDCNDD": "lcsh92_wet_jb9","HDCNDA": "lcsh92_wet_jb9","HDCNCK": "lcsh92_wet_jb9","HDMIDG": "lcsh92_wet_jb9","HDMIDE": "lcsh92_wet_jb9","HDMIDD": "lcsh92_wet_jb9","HDMIDA": "lcsh92_wet_jb9","HDMICK": "lcsh92_wet_jb9","HDMICI": "lcsh92_wet_jb9","HDMICF": "lcsh92_wet_jb9",
    "HICNEK": "dior","HICNED": "dior","HICNDL": "dior","HICNDI": "dior","HICNDG": "dior","HICNDE": "dior","HICNDD": "dior","HICNDA": "dior","HICNCK": "dior","HICNCI": "dior","HICNCH": "dior","HICNCF": "dior","HICNCB": "dior","HICNBL": "dior","HICNBK": "dior","BH21.0": "dior","BH15.0": "dior","NBF6.0": "dior","HIMIEK": "dior","HIMIDL": "dior","HIMIDI": "dior","HIMIDG": "dior","HIMIDE": "dior","HIMIDD": "dior","HIMIDA": "dior","HIMICK": "dior","HIMICI": "dior","HIMICH": "dior","HIMICF": "dior","HIMICD": "dior","HIMICB": "dior","HIMIBL": "dior",
    "HKCNEK": "gucci","HKCNED": "gucci","HKCNDL": "gucci","HKCNDI": "gucci","HKCNDG": "gucci","HKCNDE": "gucci","HKCNDD": "gucci","HKCNDA": "gucci","HKCNCK": "gucci","HKCNCI": "gucci","HKCNCF": "gucci","HKCNCD": "gucci","HKCNCB": "gucci","HKCNBL": "gucci","HKMIEK": "gucci","HKMIED": "gucci","HKMIDL": "gucci","HKMIDI": "gucci","HKMIDG": "gucci","HKMIDE": "gucci","HKMIDD": "gucci","HKMIDA": "gucci","HKMICK": "gucci",
    "HMCNFD": "hermes","HMCNFA": "hermes","HMCNEK": "hermes","HMCNED": "hermes","HMCNDL": "hermes","HMCNDI": "hermes","HMCNDG": "hermes","HMCNDE": "hermes","HMCNDD": "hermes","HMCNDA": "hermes","HMCNCK": "hermes","HMCNCI": "hermes","HMCNCH": "hermes","HMCNCF": "hermes","HMMIFD": "hermes","HMMIFA": "hermes","HMMIEK": "hermes","HMMIED": "hermes","HMMIDI": "hermes","HMMIDG": "hermes","HMMIDE": "hermes","HMMIDD": "hermes","HMMIDA": "hermes","HMMICK": "hermes","HMMICI": "hermes",
    "HNCNFD": "hennessy","HNCNFA": "hennessy","HNCNEK": "hennessy","HNCNED": "hennessy","HNCNDL": "hennessy","HNCNDI": "hennessy","HNCNDG": "hennessy","HNCNDE": "hennessy","HNCNDD": "hennessy","HNCNDA": "hennessy","HNCNCK": "hennessy","HNCNCJ": "hennessy",
    "HOCNXM": "kenzo","HOCNFI": "kenzo","HOCNFD": "kenzo","HOCNFA": "kenzo","HOCNEK": "kenzo","HOCNED": "kenzo","HOCNDL": "kenzo","HOCNDI": "kenzo","HOCNDG": "kenzo","HOCNDE": "kenzo","HOCNDD": "kenzo","HOCNDA": "kenzo","HOCNCL": "kenzo","HOMIXM": "kenzo","HOMIFI": "kenzo","HOMIFD": "kenzo","HOMIFA": "kenzo","HOMIEK": "kenzo","HOMIED": "kenzo","HOMIDL": "kenzo","HOMIDI": "kenzo","HOMIDG": "kenzo","HOMIDE": "kenzo","HOMIDD": "kenzo","HOMIDA": "kenzo","HOMICL": "kenzo",
    "HRMIXM": "kate","HRMIFI": "kate","HRMIFD": "kate","HRMIFA": "kate","HRMIEK": "kate","HRMIED": "kate","HRMIDL": "kate","HRMIDI": "kate","HRMIDG": "kate","HRMIDE": "kate",
    "BFCNXM": "nikel","BFCNFI": "nikel","BFCNFD": "nikel","BFCNFA": "nikel","BFCNEK": "nikel","BFCNED": "nikel","BFCNDL": "nikel","BFCNDI": "nikel","BFCNDG": "nikel","BFCNDF": "nikel","BFCNDE": "nikel","BFMIXM": "nikel","BFMIFI": "nikel","BFMIFD": "nikel","BFMIFA": "nikel","BFMIEK": "nikel","BFMIED": "nikel","BFMIDL": "nikel","BFMIDI": "nikel","BFMIDG": "nikel",
    "CFCNXM": "mido","CFCNFI": "mido","CFCNFD": "mido","CFCNFA": "mido","CFCNEK": "mido","CFCNEI": "mido","CFCNED": "mido","CFCNDL": "mido","CFCNDI": "mido","CFMIXM": "mido","CFMIFI": "mido","CFMIFD": "mido","CFMIFA": "mido","CFMIEK": "mido","CFMIEI": "mido","CFMIED": "mido","CFMIDL": "mido","CFMIDI": "mido",
    "DFCNXM": "ugglite","DFCNFI": "ugglite","DFCNFD": "ugglite","DFCNFA": "ugglite","DFCNEK": "ugglite","DFCNEI": "ugglite","DFCNED": "ugglite","DFMIXM": "ugglite","DFMIFD": "ugglite","DFMIFA": "ugglite","DFMIEK": "ugglite","DFMIEI": "ugglite","DFMIED": "ugglite",
    "DKCNXM": "ugg","DKCNFI": "ugg","DKCNFD": "ugg","DKCNFA": "ugg","DKCNEK": "ugg","DKCNEI": "ugg","DKCNED": "ugg","DKMIXM": "ugg","DKMIFD": "ugg","DKMIFA": "ugg","DKMIEK": "ugg","DKMIEI": "ugg","DKMIED": "ugg",
    "EICNXM": "whyred","EICNFK": "whyred","EICNFH": "whyred","EICNFA": "whyred","EICNFD": "whyred","EIMIXM": "whyred","EIMIFH": "whyred","EIMIFD": "whyred","EIMIFA": "whyred","EIMIEK": "whyred","EIRUXM": "whyred","EIRUFA": "whyred",
    "EKMIXM": "tulip","EKMIFH": "tulip","EKMIFD": "tulip","EKRUXM": "tulip","EKRUFD": "tulip",
    "FGCNXM": "lavender","FGMIXM": "lavender","FGEUXM": "lavender","FGRUXM": "lavender","FGINXM": "lavender","FGMXTC": "lavender",
    "FHCNXM": "violet","FHINXM": "violet",
    "COCNXM": "ginkgo","COMIXM": "ginkgo","COEUXM": "ginkgo","CORUXM": "ginkgo","COINXM": "ginkgo","COIDXM": "ginkgo","COMXTC": "ginkgo",
    "GGCNXM": "begonia","GGMIXM": "begonia","GGEUXM": "begonia","GGRUXM": "begonia","GGINXM": "begonia","GGIDXM": "begonia","GGMXTC": "begonia","GGLMCR": "begonia",
    "CXMIXM": "willow","CXEUXM": "willow","CXRUXM": "willow",
    "CUMIXM": "biloba","CUEUXM": "biloba","CURUXM": "biloba",
    "JOCNXM": "merlin","JOMIXM": "merlin","JOEUXM": "merlin","JORUXM": "merlin","JOINXM": "merlin","JOIDXM": "merlin","JOTRXM": "merlin","JOCLEN": "merlin","JOMXTC": "merlin","JOMXAT": "merlin","JOLMCR": "merlin",
    "JQCNXM": "lime","JQTWXM": "lime","JQMIXM": "lime","JQEUXM": "lime","JQRUXM": "lime","JQINXM": "lime","JQIDXM": "lime","JQTRXM": "lime","JQMXTC": "lime","JQLMCR": "lime",
    "KE.J22":"cannon","JECNXM": "cannon","JETWXM": "cannon","JEMIXM": "cannon","JEEUXM": "cannon","JERUXM": "cannon","JETRXM": "cannon","JELMCR": "cannon",
    "JSCNXM": "gauguin","JSTWXM": "gauguin","JSMIXM": "gauguin","JSEUXM": "gauguin","JSINXM": "gauguin","JSTRXM": "gauguin",
    "JZTWXM": "joyeuse","JZMIXM": "joyeuse","JZEUXM": "joyeuse","JZRUXM": "joyeuse","JZIDXM": "joyeuse","JZTRXM": "joyeuse","JZCLEN": "joyeuse","JZLMCR": "joyeuse",
    "JXINXM": "excalibur",
    "JWMIXM": "curtana","JWEUXM": "curtana","JWRUXM": "curtana","JWINXM": "curtana","JWTRXM": "curtana","JWMXAT": "curtana",
    "KGMIXM": "mojito","KGEUXM": "mojito","KGRUXM": "mojito","KGINXM": "mojito","KGIDXM": "mojito","KGTRXM": "mojito",
    "JWINRF": "curtana_in_rf",
    "KFTWXM": "sweet","KFMIXM": "sweet","KFEUXM": "sweet","KFRUXM": "sweet","KFINXM": "sweet","KFIDXM": "sweet","KFTRXM": "sweet","KFCLEN": "sweet","KFMXTC": "sweet","KFMXAT": "sweet","KFLMCR": "sweet","KFZAVC": "sweet",
    "EE.K19":"camellia","KSCNXM": "camellia","KSTWXM": "camellia","KSMIXM": "camellia","KSEUXM": "camellia","KSRUXM": "camellia","KSINXM": "camellia","KSIDXM": "camellia","KSTRXM": "camellia","KSTHAS": "camellia","KSCLEN": "camellia","KSLMCR": "camellia","KSMXAT": "camellia",
    "L.K10A":"chopin","KPCNDM": "chopin","KPCNXM": "chopin","KPMIXM": "chopin","KPIDXM": "chopin","KPTRXM": "chopin",
    "KNJPXM": "lilac",
    "Y.K19S":"selene","KUCNXM": "selene","KUTWXM": "selene","KUMIXM": "selene","KUEUXM": "selene","KURUXM": "selene","KUINXM": "selene","KUIDXM": "selene","KUTRXM": "selene","KUMXAT": "selene","KULMCR": "selene",
    "B.K16A":"evergo","C.K16A":"evergo","E.K16A":"evergo","T.K16A":"evergo","N.K16A":"evergo","X.K16A":"evergo","GBCNXM": "evergo","GBINXM": "evergo",
    "KTCNXM": "pissarro","KTTWXM": "pissarro","KTMIXM": "pissarro","KTEUXM": "pissarro","KTRUXM": "pissarro","KTINXM": "pissarro","KTTRXM": "pissarro",
    "GCMIXM": "spes","GCINXM": "spes","GCTRXM": "spes","GCCLEN": "spes","GCLMCR": "spes","GCMXAT": "spes","GCLMMS": "spes",
    "GKMIXM": "spesn","GKEUXM": "spesn","GKRUXM": "spesn","GKIDXM": "spesn","GKZAMT": "spesn",
    "EE.K6S":"veux","KCCNXM": "veux","KCTWXM": "veux","KCMIXM": "veux","KCEUXM": "veux","KCRUXM": "veux","KCINXM": "veux","KCIDXM": "veux","KCTRXM": "veux","KCJPXM": "veux","KCCLEN": "veux","KCLMCR": "veux","KCMXAT": "veux",
    "KETWXM": "fleur","KEMIXM": "fleur","KEEUXM": "fleur","KERUXM": "fleur","KEINXM": "fleur","KEIDXM": "fleur","KETRXM": "fleur","KECLEN": "fleur","KELMCR": "fleur","KEMXAT": "fleur","KELMMS": "fleur",
    "GDTWXM": "viva","GDMIXM": "viva","GDEUXM": "viva","GDRUXM": "viva","GDIDXM": "viva","GDTRXM": "viva","GDLMCR": "viva","GDLMMS": "viva","GDZAMT": "viva",
    "GDINXM": "vida",
    "CE.L19":"light","E.L19X":"light","JA.L19":"light","XY.L19":"light","LSCNXM": "light","LSTWXM": "light","LSMIXM": "light","LSEUXM": "light","LSRUXM": "light","LSINXM": "light","LSIDXM": "light","LSTRXM": "light","LSTHAS": "light","LSCLEN": "light","LSLMCR": "light",
    "GLTWXM": "opal","GLMIXM": "opal","GLEUXM": "opal","GLRUXM": "opal","GLCLEN": "opal","GLMXAT": "opal","GLLMCR": "opal",
    "LOCNXM": "xaga","LOTWXM": "xaga","LOMIXM": "xaga","LOEUXM": "xaga","LORUXM": "xaga","LOINXM": "xaga","LOTRXM": "xaga",
    "EE.M17":"sunstone","MQCNXM": "sunstone","MQINXM": "sunstone","MQEUXM":"sunstone","MQMIXM":"sunstone","MQTWXM":"sunstone",
    "EE.M16":"ruby","MOCNXM": "ruby","MOINXM": "ruby","MOMIXM": "ruby","MORUXM": "ruby","MOIDXM": "ruby","MOTWXM": "ruby","MOEUXM": "ruby","MOTRXM": "ruby",
    "MSCNXM": "redwood","MSTWXM": "redwood","MSMIXM": "redwood","MSEUXM": "redwood","MSRUXM": "redwood","MSINXM": "redwood","MSTRXM": "redwood",
    "FJCNXM": "davinci","FJMIXM": "davinci","FJEUXM": "davinci","FJRUXM": "davinci","FJINXM": "davinci",
    "FKCNXM": "raphael","FKMIXM": "raphael","FKEUXM": "raphael","FKRUXM": "raphael","FKINXM": "raphael",
    "GHCNXM": "phoenix","GHINXM": "phoenix",
    "GICNXM": "picasso",
    "GICMXM": "picasso_48m",
    "JKCNXM": "lmi","JKMIXM": "lmi","JKEUXM": "lmi","JKRUXM": "lmi","JKIDXM": "lmi","JKTRXM": "lmi",
    "JNCNXM": "cezanne",
    "JDCNXM": "apollo","JDTWXM": "apollo","JDMIXM": "apollo","JDEUXM": "apollo","JDRUXM": "apollo","JDINXM": "apollo","JDIDXM": "apollo","JDTRXM": "apollo","JDCLEN": "apollo","JDMXTC": "apollo","JDLMCR": "apollo",
    "E.K11A":"alioth","KHCNDM": "alioth","KHCNXM": "alioth","KHTWXM": "alioth","KHMIXM": "alioth","KHEUXM": "alioth","KHRUXM": "alioth","KHINXM": "alioth","KHIDXM": "alioth","KHTRXM": "alioth",
    "KJCNDM": "ares","KJCNXM": "ares","KJINXM": "ares",
    "LMCNXM": "munch","LMTWXM": "munch","LMMIXM": "munch","LMEUXM": "munch","LMRUXM": "munch","LMINXM": "munch","LMIDXM": "munch","LMTRXM": "munch",
    "LJCNXM": "ingres","LJTWXM": "ingres","LJMIXM": "ingres","LJEUXM": "ingres","LJRUXM": "ingres","LJIDXM": "ingres","LJTRXM": "ingres",
    "E.L11A":"rubens","LNCNXM": "rubens","LNCNDM":"rubens",
    "EE.L11":"matisse","LKCNXM": "matisse",
    "LFCNXM": "diting","LFTWXM": "diting","LFMIXM": "diting","LFEUXM": "diting","LFRUXM": "diting","LFTRXM": "diting","LFCLEN": "diting","LFLMCR": "diting","LFMXAT": "diting","LFJPXM": "diting","EE.L12":"diting",
    "MNCNXM": "mondrian","E.M11A":"mondrian",
    "MKCNXM": "socrates",
    "MMCNXM": "rembrandt",
    "LYCNXM": "yunluo","LYTWXM": "yunluo","LYMIXM": "yunluo","LYEUXM": "yunluo","LYRUXM": "yunluo","LYINXM": "yunluo","LYIDXM": "yunluo","LYTRXM": "yunluo",
    "HQCNXM": "omega","HQCNFI": "omega","HQCNFD": "omega","HQCNFA": "omega","HQCNEK": "omega","HQCNED": "omega","HQCNDI": "omega","HQCNDG": "omega","HQCNDE": "omega",
    "EFCNXM": "ysl","EFCNFH": "ysl","EFCNFD": "ysl","EFCNFA": "ysl","EFMIXM": "ysl","EFMIFH": "ysl","EFMIFD": "ysl","EFMIFA": "ysl","EFRUXM": "ysl","EFRUFA": "ysl","EFMSFD": "ysl",
    "CLMIXM": "tiare","CLEUXM": "tiare","CLRUXM": "tiare","CLINXM": "tiare",
    "FFINXM": "onc",
    "GMTWXM": "ice","GMMIXM": "ice","GMEUXM": "ice","GMRUXM": "ice","GMINXM": "ice","GMIDXM": "ice",
    "CRINRF": "angelicain",
    "GFTWXM": "frost","GFMIXM": "frost","GFEUXM": "frost","GFRUXM": "frost","GFIDXM": "frost",
    "EJMIXM": "beryllium","EJMIFI": "beryllium","EJMIFH": "beryllium","EJMIFD": "beryllium","EJRUXM": "beryllium","EJRUFD": "beryllium",
    "JRINXM": "shiva",
    "JPINXM": "gram",
    "JFTWXM": "citrus","JFMIXM": "citrus","JFEUXM": "citrus","JFRUXM": "citrus","JFINXM": "citrus","JFIDXM": "citrus","JFTRXM": "citrus",
    "LUTWXM": "rock","LUMIXM": "rock","LUEUXM": "rock","LURUXM": "rock","LUINXM": "rock","LUIDXM": "rock","LUTRXM": "rock",
    "FFTWXM": "rosemary_p","FFMIXM": "rosemary_p","FFEUXM": "rosemary_p","FFRUXM": "rosemary_p","FFIDXM": "rosemary_p","FFTRXM": "rosemary_p",
    "JGMIXM": "surya","JGEUXM": "surya","JGRUXM": "surya","JGINXM": "surya","JGIDXM": "surya","JGTRXM": "surya",
    "JUTWXM": "vayu","JUMIXM": "vayu","JUEUXM": "vayu","JURUXM": "vayu","JUINXM": "vayu","JUIDXM": "vayu","JUTRXM": "vayu",
    "MPTWXM": "moonstone","MPMIXM": "moonstone","MPEUXM": "moonstone","MPRUXM": "moonstone","MPINXM":"moonstone","MPIDXM":"moonstone",
    "CVRUXM":"earth","CVCNXM":"earth","CVCLEN":"earth","CVLMCR":"earth","CVINXM":"earth","CVEUXM":"earth","CVIDXM":"earth","CVTRXM":"earth","CVMIXM":"earth","EE.C3T":"earth","CVTWXM":"earth",
    "GBTWXM": "evergreen","GBMIXM": "evergreen","GBEUXM": "evergreen","GBRUXM": "evergreen","GBTRXM":"evergreen",
    "JOTWXM": "merlin",
    "KLRUXM": "rosemary","KLTWXM": "rosemary","KLEUXM": "rosemary","KLTRXM": "rosemary","KLMIXM": "rosemary","KLIDXM": "rosemary","KLINXM": "rosemary","KLLMCR": "rosemary","KLCLEN":"rosemary","KLMXAT":"rosemary","KLMXTC":"rosemary","KLZAMT":"rosemary","KLZAVC":"rosemary",
    "JLB54.0": "taurus",
    "BL31.0": "wt98007",
    "MTMIXM":"tapas","MTINXM":"tapas","MTTRXM":"tapas",
    "MGEUXM":"topaz","MGMIXM":"topaz","MGIDXM":"topaz","MGRUXM":"topaz",
    "MRCNXM":"marble",
    "GOMIXM":"water","GOTWXM":"water",
    "MUIDXM":"xun",
    "MACNXM":"ishtar",
    "HGEUXM":"sweet_k6a","HGMIXM":"sweet_k6a","HGRUXM":"sweet_k6a",
    "MZCNXM":"pipa","LZCNDM":"dagu","MZMIXM":"pipa","MZTRXM":"pipa",
    "RUBYKRGlobal":"ruby",
    "SWEETK6AIDGlobal":"sweet_k6a",
    "MNEUXM":"mondrian","MNMIXM":"mondrian","MNTWXM":"mondrian","MNTRXM":"mondrian","MNRUXM":"mondrian",
    "MRINXM":"marble","MRMIXM":"marble","MREUXM":"marble","MRTRXM":"marble","MRIDXM":"marble","MRRUXM":"marble","MRTWXM":"marble",
    "MAEUXM":"ishtar","MQCNDM":"sunstone","MAMIXM":"ishtar","E.M17X":"sunstone","L.M17X":"sunstone",
    "MICNXM":"yuechu","MICNDM":"yuechu",
    "LHCNXM":"pearl",
    "KE.K19":"camellia",
    "JBEUHG": "umi",
    "JBEUOR": "umi",
    "JBEUTF": "umi",
    "JBEUVF": "umi",
    "JBEUSF": "umi",
    "JBEUTI": "umi",
    "JIEUHG": "monet",
    "JIEUOR": "monet",
    "JIEUTF": "monet",
    "JIEUVF": "monet",
    "JIEUSF": "monet",
    "JIEUTI": "monet",
    "KBEUHG": "venus",
    "KBEUOR": "venus",
    "KBEUTF": "venus",
    "KBEUVF": "venus",
    "KBEUSF": "venus",
    "KBEUTI": "venus",
    "KAEUOR": "star",
    "KAEUVF": "star",
    "KICNDM": "renoir",
    "KIEUHG": "renoir",
    "KIEUOR": "renoir",
    "KIEUTF": "renoir",
    "KIEUVF": "renoir",
    "KIEUSF": "renoir",
    "GFTRXM":"frost",
    "KIEUTI": "renoir",
    "KWEUHG": "agate",
    "KWEUOR": "agate",
    "KWEUTF": "agate",
    "KWEUBY": "agate",
    "KWEUVF": "agate",
    "KWEUSF": "agate",
    "KWEUTI": "agate",
    "KDEUOR": "vili",
    "KDEUTF": "vili",
    "KDEUVF": "vili",
    "KDEUSF": "vili",
    "KOEUHG": "lisa",
    "KOEUOR": "lisa",
    "KOEUTF": "lisa",
    "KOEUBY": "lisa",
    "KOEUVF": "lisa",
    "KOEUSF": "lisa",
    "KOEUTI": "lisa",
    "LECNDM": "unicorn",
    "LACNDM": "thor",
    "MCCNDM": "fuxi",
    "MBCNDM": "nuwa",
    "MACNDM": "ishtar",
    "MARUXM": "ishtar",
    "FNEUOR": "toco",
    "FNEUTF": "toco",
    "FNEUVF": "toco",
    "KMCNDM": "odin",
    "LRCNDM": "zizhan",
    "EE.K81": "enuma",
    "MZCNDM": "pipa",
    "MYCNXM": "liuqin",
    "MYCNDM": "liuqin",
    "KVCNDM": "mona",
    "LLCNDM": "ziyi",
    "JCEUHG": "lancelot",
    "JCEUOR": "lancelot",
    "JCEUTF": "lancelot",
    "JCEUVF": "lancelot",
    "JCEUSF": "lancelot",
    "CDEUTF": "dandelion",
    "CDEUVF": "dandelion",
    "CDEUSF": "dandelion",
    "CDEUTI": "dandelion",
    "CSEUOR": "angelican",
    "CZEUBY": "dandelion_c3l2",
    "CZEUSF": "dandelion_c3l2",
    "GEEUHG": "fog",
    "GEEUOR": "fog",
    "GEEUTF": "fog",
    "GEEUVF": "fog",
    "GEEUSF": "fog",
    "GEEUTI": "fog",
    "CVEUHG": "earth",
    "CVEUTF": "earth",
    "CVEUBY": "earth",
    "CVEUVF": "earth",
    "CVEUSF": "earth",
    "CVMXAT": "earth",
    "JOEUHG": "merlin",
    "JOEUOR": "merlin",
    "JOEUTF": "merlin",
    "JOEUVF": "merlin",
    "JOEUSF": "merlin",
    "JOEUTI": "merlin",
    "JQCNDM": "lime",
    "JQEUHG": "lime",
    "JQEUOR": "lime",
    "JQEUTF": "lime",
    "JQEUVF": "lime",
    "JQEUSF": "lime",
    "JQEUTI": "lime",
    "JEEUOR": "cannon",
    "JEEUTF": "cannon",
    "JEEUVF": "cannon",
    "JEEUSF": "cannon",
    "JEEUTI": "cannon",
    "JSEUHG": "gauguin",
    "JSEUOR": "gauguin",
    "JSEUTF": "gauguin",
    "JSEUVF": "gauguin",
    "JSEUSF": "gauguin",
    "JSEUTI": "gauguin",
    "JZEUOR": "joyeuse",
    "JZEUTF": "joyeuse",
    "JZEUVF": "joyeuse",
    "JZEUSF": "joyeuse",
    "KFEUHG": "sweet",
    "KFEUOR": "sweet",
    "KFEUTF": "sweet",
    "KFEUVF": "sweet",
    "KFEUSF": "sweet",
    "KFEUTI": "sweet",
    "KSEUHG": "camellia",
    "KSEUOR": "camellia",
    "KSEUTF": "camellia",
    "KSEUVF": "camellia",
    "KSEUSF": "camellia",
    "KSEUTI": "camellia",
    "KLEUOR": "rosemary",
    "KLEUTF": "rosemary",
    "KLEUVF": "rosemary",
    "KLEUSF": "rosemary",
    "KUEUHG": "selene",
    "KUEUOR": "selene",
    "KUEUTF": "selene",
    "KUEUBY": "selene",
    "KUEUVF": "selene",
    "KUEUSF": "selene",
    "KUZAVC": "selene",
    "KUZAMT": "selene",
    "KTCNDM": "pissarro",
    "GKEUHG": "spesn",
    "GKEUOR": "spesn",
    "GKEUTF": "spesn",
    "GKEUBY": "spesn",
    "GKEUVF": "spesn",
    "GKEUSF": "spesn",
    "GKEUTI": "spesn",
    "KCEUHG": "veux",
    "KCEUOR": "veux",
    "KCEUTF": "veux",
    "KCEUBY": "veux",
    "KCEUVF": "veux",
    "KCEUSF": "veux",
    "KCEUTI": "veux",
    "KEEUOR": "fleur",
    "KEEUBY": "fleur",
    "KEEUSF": "fleur",
    "LSEUHG": "light",
    "LSEUOR": "light",
    "LSEUTF": "light",
    "LSEUBY": "light",
    "LSEUVF": "light",
    "LSEUSF": "light",
    "LSEUTI": "light",
    "GLEUHG": "opal",
    "GLEUOR": "opal",
    "GLEUTF": "opal",
    "GLEUBY": "opal",
    "GLEUVF": "opal",
    "GLEUSF": "opal",
    "LOCNDM": "xaga",
    "MOCNDM": "ruby",
    "MOCLEN": "ruby",
    "MOLMCR": "ruby",
    "MOMXAT": "ruby",
    "MOLMMS": "ruby",
    "MRCNDM": "marble",
    "HGIDXM": "sweet_k6a",
    "HGTRXM": "sweet_k6a",
    "HZMIXM": "sea",
    "HZEUXM": "sea",
    "HZRUXM": "sea",
    "HZTRXM": "sea",
    "HZTWXM":"sea",
    "JDEUHG": "apollo",
    "JDEUOR": "apollo",
    "JDEUTF": "apollo",
    "JDEUVF": "apollo",
    "JDEUSF": "apollo",
    "JDEUTI": "apollo",
    "KKEUHG": "haydn",
    "KKEUOR": "haydn",
    "KKEUTF": "haydn",
    "KKEUBY": "haydn",
    "KKEUVF": "haydn",
    "KKEUSF": "haydn",
    "KKEUTI": "haydn",
    "LKCNDM": "matisse",
    "LFCNDM": "diting",
    "MNCNDM": "mondrian",
    "MKCNDM": "socrates",
    "MMCNDM": "rembrandt",
    "EE.L83": "yunluo",
    "LYCNDM": "yunluo",
    "GOINXM": "water",
    "MPTRXM": "moonstone",
    "EE.L3A":"psyche",
    "CVEUOR": "earth",
    "CVZAMT": "earth",
    "CVLMMS":"earth",
    "MSIDXM": "redwood",
    "GMMXTC": "ice",
    "GMLMCR": "ice",
    "GMZAVC": "ice",
    "GOEUXM": "water",
    "GOEUSF": "water",
    "GOCLEN": "water",
    "GOMXTC": "water",
    "GOLMCR": "water",
    "MATWXM":"ishtar",
    "MZINXM":"pipa",
    "E.M16T":"marble",
    "MXMIXM":"fire",
    "MXEUXM":"fire",
    "MXRUXM":"fire",
    "X.L11A":"rubens",
    "YX.K19":"camellia",
    "KE.K16":"pissarro",
    "EE.M11":"socrates",
    "EE.L19":"light",
    "JCG.M2": "nuwa",
    "MWCNXM": "sky",
    "MWEUXM":"sky",
    "DEE.M1": "ishtar",
    "CVZAVC": "earth",
    "MOKRXM": "ruby",
    "GMZAMT": "ice",
    "GOEUHG": "water",
    "GOZAVC": "water",
    "E.M11R":"rembrandt",
    "MZTWXM":"pipa",
    "MZEUXM":"pipa",
    "EE.L2S":"unicorn",
    "FDEUHG":"tucana",
    "FDEUOR":"tucana",
    "FDEUTF":"tucana",
    "FDEUVF":"tucana",
    "FDEUTI":"tucana",
    "CVEUTI":"earth",
    "CVGTTG":"earth",
    "CXEUHG":"willow",
    "CXEUOR":"willow",
    "CXEUTF":"willow",
    "CXEUVF":"willow",
    "CXEUTI":"willow",
    "E.J19S":"lime",
    "L.J19S":"lime",
    "KNJPSB":"lilac",
    "GOEUBY":"water",
    "GORUXM":"water",
    "GOMXAT":"water",
    "GOZAMT":"water",
    "GOIDXM":"water",
    "MWINXM":"sky",
    "MXINXM":"fire",
    "MXIDXM":"fire",
    "MHCNDM":"yudi",
    "MHCNXM":"yudi",
    "MLCNDM":"corot",
    "MLCNXM":"corot",
    "MWMIXM":"sky",
    "MVCNXM":"babylon",
    "MVCNDM":"babylon",
    "EE.M81": "liuqin",
    "MXTRXM": "fire",
    "EE.M19": "sky",
    "MZRUXM": "pipa",
    "MZIDXM": "pipa",
    "MUEUXM": "xun",
    "MUTWXM": "xun",
    "MUMIXM": "xun",
    "NRCNXM": "garnet",
    "NQCNXM": "gold",
    "MUCNXM": "xun",
    "NOCNXM":"zircon",
    "NOCNDM":"zircon",
    "MWTWXM":"sky",
    "Mioneplus": "mione_plus","MioneplusCDMA": "mione_plus","NativeMioneplus": "mione_plus","plus-ota-QDR68": "mione_plus","plus-ota-QDR66": "mione_plus","plus-ota-QDR65.zip": "mione_plus","plus-ota-QDQ61.zip": "mione_plus","plus-ota-QDO53.zip": "mione_plus",
    "MI2": "aries","MI2Beta": "aries","MI2HK": "aries","MI2TW": "aries","NativeMI2": "aries","MI2Global": "aries",
    "MI2A": "taurus","MI2ABeta": "taurus","NativeMI2A": "taurus",
    "MI3TD": "pisces",
    "XUN": "xun",
    "REMBRANDTEPSTDEE":"rembrandt",
    "FIREIDGlobal":"fire",
    "MI3WMI4W": "cancro","MI3WHK": "cancro","MI3WTW": "cancro","MI3WMY": "cancro","MI3WSG": "cancro","MI3WMI4WGlobal": "cancro","MI3WGlobal": "cancro",
    "MI4LTECT": "cancro_lte_ct",
    "MI4i": "ferrari","MI4iGlobal": "ferrari","FERRARIGlobal": "ferrari",
    "MI4c": "libra","LIBRA": "libra",
    "MI4s": "aqua","AQUA": "aqua",
    "MI5": "gemini","MI5Global": "gemini",
    "MI5S": "capricorn","MI5SGlobal": "capricorn",
    "MI5SPlus": "natrium","NATRIUM": "natrium","MI5SPlusGlobal": "natrium",
    "MI5C": "meri","MERI": "meri",
    "MI5X": "tiffany","TIFFANY": "tiffany",
    "MI6":"sagit","MI6Alpha": "sagit","MI6Global": "sagit",
    "MI6X": "wayne",
    "MI8": "dipper","DIPPER": "dipper","MI8Global": "dipper","MI8RUGlobal": "dipper",
    "MI8UD": "equuleus","EQUULEUS": "equuleus","MI8UDGlobal": "equuleus","MI8ProRUGlobal": "equuleus",
    "MI8Explorer": "ursa",
    "MI8Lite": "platina","PLATINA": "platina","MI8LiteGlobal": "platina","PLATINARUGlobal": "platina",
    "CEPHEUS": "cepheus",
    "CEPHEUSGlobal": "cepheus","CEPHEUSEEAGlobal": "cepheus","CEPHEUSRUGlobal": "cepheus","CEPHEUSLMCRGlobal": "cepheus","CEPHEUSMXTCGlobal": "cepheus",
    "CRUX": "crux",
    "UMI": "umi","UMIPRE": "umi","UMIGlobal": "umi","UMIEEAGlobal": "umi","UMIRUGlobal": "umi","UMIINGlobal": "umi","UMIIDGlobal": "umi","UMITRGlobal": "umi",
    "CMI": "cmi","CMIPRE": "cmi","CMIGlobal": "cmi","CMIEEAGlobal": "cmi",
    "MONETTWGlobal": "monet","MONETGlobal": "monet","MONETEEAGlobal": "monet","MONETJPKDGlobal": "monet","MONETKRGUGlobal": "monet","MONETKRKTGlobal": "monet","MONETKRSKGlobal": "monet",
    "VANGOGH": "vangogh","VANGOGHPRE": "vangogh",
    "CAS": "cas","CASPRE": "cas",
    "VENUS": "venus","VENUSPRE": "venus","VENUSTWGlobal": "venus","VENUSGlobal": "venus","VENUSEEAGlobal": "venus","VENUSRUGlobal": "venus","VENUSIDGlobal": "venus","VENUSTRGlobal": "venus","VENUSMXTCGlobal": "venus",
    "HAYDN": "haydn","HAYDNPRE": "haydn","HAYDNGlobal": "haydn","HAYDNEEAGlobal": "haydn","HAYDNINGlobal": "haydn",
    "THYME": "thyme","THYMEPRE": "thyme",
    "COURBETGlobal": "courbet","COURBETEEAGlobal": "courbet","COURBETRUGlobal": "courbet","COURBETINGlobal": "courbet","COURBETIDGlobal": "courbet","COURBETTRGlobal": "courbet","COURBETLMCRGlobal": "courbet","COURBETMXTCGlobal": "courbet",
    "STAR": "star","STARPRE": "star","STAREPXY": "star","STARGlobal": "star","STAREEAGlobal": "star","STARINGlobal": "star","STARIDGlobal": "star",
    "RENOIR": "renoir","RENOIRPRE": "renoir","RENOIREPYY": "renoir","RENOIRTWGlobal": "renoir","RENOIRGlobal": "renoir","RENOIREEAGlobal": "renoir","RENOIRRUGlobal": "renoir","RENOIRLMCRGlobal": "renoir","RENOIRMXTCGlobal": "renoir","RENOIRCLENGlobal": "renoir","RENOIRJPGlobal": "renoir",
    "AGATETWGlobal": "agate","AGATEGlobal": "agate","AGATEEEAGlobal": "agate","AGATERUGlobal": "agate","AGATEIDGlobal": "agate","AGATETRGlobal": "agate","AGATECLENGlobal": "agate","AGATEMXATGlobal": "agate",
    "VILITWGlobal": "vili","VILIGlobal": "vili","VILIEEAGlobal": "vili","VILIRUGlobal": "vili","VILIINGlobal": "vili","VILIIDGlobal": "vili","VILITRGlobal": "vili","VILIJPGlobal": "vili","VILICLENGlobal": "vili","VILIMXATGlobal": "vili",
    "LISA":"lisa","LISAPRE": "lisa","MONAPRE": "lisa","LISATWGlobal": "lisa","LISAGlobal": "lisa","LISAEEAGlobal": "lisa","LISARUGlobal": "lisa","LISAINGlobal": "lisa","LISATRGlobal": "lisa","LISACLENGlobal": "lisa","LISAMXTCGlobal": "lisa","LISAMXATGlobal": "lisa",
    "PISSARROINGlobal": "pissarro","PISSARROINFKGlobal": "pissarroin",
    "CUPID": "cupid","CUPIDEPXY": "cupid","CUPIDTWGlobal": "cupid","CUPIDGlobal": "cupid","CUPIDEEAGlobal": "cupid","CUPIDRUGlobal": "cupid","CUPIDIDGlobal": "cupid","CUPIDTRGlobal": "cupid","CUPIDLMCRGlobal": "cupid","CUPIDMXATGlobal": "cupid",
    "ZEUS": "zeus","ZEUSEPXY": "zeus","ZEUSEPSTDEE": "zeus","ZEUSTWGlobal": "zeus","ZEUSGlobal": "zeus","ZEUSEEAGlobal": "zeus","ZEUSRUGlobal": "zeus","ZEUSINGlobal": "zeus","ZEUSIDGlobal": "zeus","ZEUSTRGlobal": "zeus",
    "PSYCHE": "psyche","PSYCHEPRE": "psyche","PSYCHETWGlobal": "psyche","PSYCHEGlobal": "psyche","PSYCHEEEAGlobal": "psyche","PSYCHERUGlobal": "psyche",
    "DAUMIER": "daumier",
    "MAYFLY": "mayfly","MAYFLYDEMO":"mayfly",
    "UNICORN": "unicorn",
    "THOR": "thor",
    "XUNIDGlobal":"xun",
    "TAOYAOTWGlobal": "taoyao","TAOYAOGlobal": "taoyao","TAOYAOEEAGlobal": "taoyao","TAOYAORUGlobal": "taoyao","TAOYAOIDGlobal": "taoyao","TAOYAOTRGlobal": "taoyao","TAOYAOLMCRGlobal": "taoyao","TAOYAOCLENGlobal": "taoyao",
    "PLATOTWGlobal": "plato","PLATOGlobal": "plato","PLATOEEAGlobal": "plato","PLATORUGlobal": "plato","PLATOIDGlobal": "plato","PLATOTRGlobal": "plato","PLATOCLENGlobal": "plato","PLATOLMCRGlobal": "plato",
    "FUXI": "fuxi","FUXIEPSTDEE": "fuxi","FUXITWGlobal": "fuxi","FUXIGlobal": "fuxi","FUXIEEAGlobal": "fuxi","FUXIRUGlobal": "fuxi","FUXITRGlobal": "fuxi",
    "NUWA": "nuwa","NUWAEPSTDEE": "nuwa","NUWATWGlobal": "nuwa","NUWAGlobal": "nuwa","NUWAEEAGlobal": "nuwa","NUWARUGlobal": "nuwa","NUWATRGlobal": "nuwa","NUWAINGlobal":"nuwa",
    "MI8SE": "sirius","SIRIUS": "sirius",
    "GRUS": "grus","GRUSGlobal": "grus","GRUSEEAGlobal": "grus","GRUSRUGlobal": "grus",
    "PYXIS": "pyxis","PYXISGlobal": "pyxis","PYXISEEAGlobal": "pyxis","PYXISRUGlobal": "pyxis",
    "VELA": "vela",
    "LAURUS": "laurus",
    "TUCANA": "tucana","TUCANAGlobal": "tucana","TUCANAEEAGlobal": "tucana","TUCANARUGlobal": "tucana","TUCANAIDGlobal": "tucana","TUCANAMXTCGlobal": "tucana",
    "MINote": "virgo","MINoteGlobal": "virgo",
    "MINoteCT": "virgo_lte_ct",
    "MINotePro": "leo",
    "MINote2": "scorpio","MINote2Global": "scorpio",
    "MINote3": "jason","JASON": "jason","MINote3Global": "jason",
    "TOCOGlobal": "toco","TOCOEEAGlobal": "toco","TOCORUGlobal": "toco","TOCOTRGlobal": "toco",
    "MIMAX": "hydrogen",
    "MIMAXGlobal": "hydrogen",
    "MIMAX652": "helium","MIMAXPro": "helium","MIMAX652Global": "helium",
    "MIMAX2": "oxygen","OXYGEN": "oxygen","MIMAX2Global": "oxygen",
    "MIMAX3": "nitrogen","NITROGEN": "nitrogen","MIMAX3Global": "nitrogen","NITROGENRUGlobal": "nitrogen",
    "MIMIX": "lithium","MIMIXGlobal": "lithium",
    "MIMIX2": "chiron","CHIRON": "chiron","MIMIX2Global": "chiron",
    "MIMIX2S": "polaris","POLARIS": "polaris","MIMIX2SGlobal": "polaris","MIMIX2SRUGlobal": "polaris",
    "MIMIX3": "perseus","MIMIX3Global": "perseus","PERSEUSH3GGlobal": "perseus","MIMIX3RUGlobal": "perseus",
    "ANDROMEDA": "andromeda","ANDROMEDAGlobal": "andromeda","ANDROMEDAEEAGlobal": "andromeda",
    "CETUS": "cetus","CETUSPRE": "cetus",
    "ODIN": "odin","ODINPRE": "odin",
    "ZIZHAN": "zizhan",
    "MIPAD": "mocha","MOCHA": "mocha","MIPADGlobal": "mocha","MOCHAGlobal": "mocha",
    "MIPAD2": "latte",
    "MIPAD3": "cappu",
    "SKYGlobal": "sky",
    "GARNET": "garnet",
    "ZIRCON": "zircon",
    "GOLD": "gold",
    "MIPAD4": "clover","CLOVER": "clover",
    "NABU": "nabu","NABUPRE": "nabu","NABUDEMO": "nabu","NABUEPLITEE": "nabu","NABUTWGlobal": "nabu","NABUGlobal": "nabu","NABUEEAGlobal": "nabu","NABURUGlobal": "nabu","NABUINGlobal": "nabu","NABUTRGlobal": "nabu","NABUEPSTDEE":"nabu",
    "ELISH": "elish","ELISHPRE": "elish","ELISHEPSTDEE": "elish",
    "ENUMA": "enuma","ENUMAPRE": "enuma","ENUMAEPTBKJ": "enuma","ENUMADEMO": "enuma",
    "DAGU": "dagu","DAGUDEMO":"dagu",
    "MONA":"mona",
    "ZIJIN": "zijin",
    "ZIYI": "ziyi","ZIYITWGlobal": "ziyi","ZIYIGlobal": "ziyi","ZIYIEEAGlobal": "ziyi","ZIYIRUGlobal": "ziyi","ZIYITRGlobal": "ziyi",
    "TISSOT": "tissot",
    "JASMINEGlobal": "jasmine",
    "DAISYGlobal": "daisy",
    "LAURELSPROUTGlobal": "laurel","LAURELSPROUTEEAGlobal": "laurel",
    "MIPLAY": "lotus","LOTUS": "lotus","MIPLAYGlobal": "lotus","MIPLAYRUGlobal": "lotus",
    "HMTD": "wt93007","HM2": "wt93007",
    "HMW": "wt98007","HM2W": "wt98007","HM2WHK": "wt98007","HM2WTW": "wt98007","HMWSGGlobal": "wt98007","HMWSGP": "wt98007","HM2WSGP": "wt98007","HMWGlobal": "wt98007","HM2WGlobal": "wt98007",
    "HM1SWC": "armani","H2A": "armani","HM1SWCGlobal": "armani","H2AGlobal": "armani",
    "HM1STD": "wt93807","H2S82TD": "wt93807","HM1SLTE": "wt96007","HM2014501": "wt96007","WT96007": "wt96007",
    "HM2XTD": "wt86047","HM2014813": "wt86047",
    "HM2XWC": "wt88047","HM2014811": "wt88047","HM2XWCGlobal": "wt88047","HM2014811Global": "wt88047",
    "HM2XTDPro": "wt86047_pro","HM2XWCPro": "wt88047_pro","HM2XWCProGlobal": "wt88047_pro",
    "HM2A": "lte26007","HM2XLCLTE": "lte26007",
    "HM3": "ido_xhdpi","HM3Global": "ido_xhdpi",
    "HM3S": "land","LAND": "land","HM3SGlobal": "land",
    "HM4": "prada","PRADA": "prada","HM4Global": "prada",
    "HM4Pro": "markw","MARKW": "markw","HM4ProGlobal": "markw",
    "HM4A": "rolex","ROLEX": "rolex","HM4AGlobal": "rolex",
    "HM4X": "santoni","HM4XGlobal": "santoni",
    "HM5": "rosy","ROSY": "rosy","HM5Global": "rosy","HM5RUGlobal": "rosy",
    "HM5A": "riva","RIVA": "riva","HM5AGlobal": "riva",
    "HM5Plus": "vince","VINCE": "vince","HM5PlusGlobal": "vince","HM5PlusRUGlobal": "vince",
    "HM6": "cereus","CEREUS": "cereus","HM6Global": "cereus","HM6RUGlobal": "cereus","CEREUSRUGlobal": "cereus",
    "HM6A": "cactus","CACTUS": "cactus","HM6AGlobal": "cactus","CACTUSGlobal": "cactus","HM6ARUGlobal": "cactus","CACTUSRUGlobal": "cactus",
    "HM6Pro": "sakura","SAKURA": "sakura","HM6ProINGlobal": "sakura","SAKURAINDIAGlobal": "sakura",
    "ONCLITE": "onclite","ONCLITEGlobal": "onclite","ONCLITEEEAGlobal": "onclite","ONCLITERUGlobal": "onclite","ONCLITEINGlobal": "onclite","ONCLITEMXTCGlobal": "onclite",
    "PINE": "pine","PINEGlobal": "pine","PINEEEAGlobal": "pine","PINERUGlobal": "pine","PINEINGlobal": "pine",
    "OLIVE": "olive",
    "OLIVEGlobal": "olive","OLIVEEEAGlobal": "olive","OLIVERUGlobal": "olive","OLIVEINGlobal": "olive","OLIVEIDGlobal": "olive",
    "OLIVELITE": "olivelite","OLIVELITEGlobal": "olivelite","OLIVELITEEEAGlobal": "olivelite","OLIVELITERUGlobal": "olivelite","OLIVELITEINGlobal": "olivelite","OLIVELITEIDGlobal": "olivelite","OLIVELITEMXTCGlobal": "olivelite",
    "OLIVEWOODINGlobal": "olivewood","OLIVEWOODIDGlobal": "olivewood",
    "ATOM": "atom","ATOMPRE": "atom",
    "BOMB": "bomb","BOMBPRE": "bomb",
    "LANCELOT": "lancelot","LANCELOTGlobal": "lancelot","LANCELOTEEAGlobal": "lancelot","LANCELOTRUGlobal": "lancelot","LANCELOTINGlobal": "lancelot","LANCELOTIDGlobal": "lancelot","LANCELOTTRGlobal": "lancelot","LANCELOTCLENGlobal": "lancelot","LANCELOTMXTCGlobal": "lancelot","LANCELOTMXATGlobal": "lancelot","LANCELOTLMCRGlobal": "lancelot",
    "DANDELION": "dandelion","DANDELIONGlobal": "dandelion","DANDELIONEEAGlobal": "dandelion","DANDELIONRUGlobal": "dandelion","DANDELIONINGlobal": "dandelion","DANDELIONIDGlobal": "dandelion","DANDELIONTRGlobal": "dandelion","DANDELIONMXTCGlobal": "dandelion","DANDELIONMXATGlobal": "dandelion","DANDELIONLMCRGlobal": "dandelion","DANDELIONZAMTGlobal": "dandelion",
    "ANGELICAGlobal": "angelica","ANGELICAEEAGlobal": "angelica","ANGELICAININGlobal": "angelica","ANGELICAIDGlobal": "angelica","ANGELICATRGlobal": "angelica","ANGELICAMXTCGlobal": "angelica","ANGELICAMXATGlobal": "angelica","ANGELICANGlobal": "angelican","ANGELICANEEAGlobal": "angelican","ANGELICANRUGlobal": "angelican",
    "CATTAILINGlobal": "cattail",
    "DANDELIONC3L2": "dandelion_c3l2","DANDELIONC3L2TWGlobal": "dandelion_c3l2","DANDELIONC3L2Global": "dandelion_c3l2","DANDELIONC3L2EEAGlobal": "dandelion_c3l2","DANDELIONC3L2RUGlobal": "dandelion_c3l2","DANDELIONC3L2INGlobal": "dandelion_c3l2","DANDELIONC3L2IDGlobal": "dandelion_c3l2","DANDELIONC3L2CLENGlobal": "dandelion_c3l2","DANDELIONC3L2MXATGlobal": "dandelion_c3l2","DANDELIONC3L2LMCRGlobal": "dandelion_c3l2","DANDELIONC3L2ZAMTGlobal": "dandelion_c3l2",
    "FOGTWGlobal": "fog","FOGGlobal": "fog","FOGEEAGlobal": "fog","FOGRUGlobal": "fog","FOGINGlobal": "fog","FOGIDGlobal": "fog","FOGTRGlobal": "fog","FOGCLENGlobal": "fog","FOGMXATGlobal": "fog","FOGLMCRGlobal": "fog","FOGZAMTGlobal": "fog",
    "HMNoteTD": "lcsh92_wet_xm_td","H3TD": "lcsh92_wet_xm_td",
    "HMNoteW": "lcsh92_wet_jb9","H3W": "lcsh92_wet_jb9","HMNoteWGlobal": "lcsh92_wet_jb9","H3WGlobal": "lcsh92_wet_jb9",
    "HMNoteLTE": "dior","H3LTE": "dior","HMNoteLTEGlobal": "dior","H3LTEGlobal": "dior",
    "HMNote1S": "gucci","GUCCI": "gucci","HMNote1SGlobal": "gucci",
    "HMNote2": "hermes","HERMES": "hermes","HMNote2Global": "hermes",
    "HMNote3": "hennessy",
    "HMNote3Pro": "kenzo","HMNote3CT": "kenzo","HMNote3ProGlobal": "kenzo","HMNote3CTGlobal": "kenzo",
    "HMNote3ProtwGlobal": "kate",
    "HMNote4": "nikel","HMNote4Global": "nikel",
    "HMNote4X": "mido","HMNote4XGlobal": "mido","MIDOGlobal": "mido",
    "HMNote5ALITE": "ugglite","UGGLITE": "ugglite","HMNote5ALITEGlobal": "ugglite",
    "HMNote5A":"ugg","HMNote5AGlobal": "ugg",
    "HMNote5":"whyred","WHYRED": "whyred","HMNote5Global": "whyred","HMNote5HMNote5ProGlobal": "whyred","WHYREDGlobal": "whyred","HMNote5RUGlobal": "whyred",
    "HMNote6ProGlobal": "tulip","TULIPGlobal": "tulip","HMNote6ProRUGlobal": "tulip",
    "LAVENDER": "lavender","LAVENDERGlobal": "lavender","LAVENDEREEAGlobal": "lavender","LAVENDERRUGlobal": "lavender","LAVENDERINGlobal": "lavender","LAVENDERMXTCGlobal": "lavender",
    "VIOLET": "violet","VIOLETINGlobal": "violet",
    "GINKGO": "ginkgo","GINKGOGlobal": "ginkgo","GINKGOEEAGlobal": "ginkgo","GINKGORUGlobal": "ginkgo","GINKGOINGlobal": "ginkgo","GINKGOIDGlobal": "ginkgo","GINKGOMXTCGlobal": "ginkgo",
    "BEGONIA": "begonia","BEGONIAGlobal": "begonia","BEGONIAEEAGlobal": "begonia","BEGONIARUGlobal": "begonia","BEGONIAININGlobal": "begonia","BEGONIAIDGlobal": "begonia","BEGONIAMXTCGlobal": "begonia",
    "WILLOWGlobal": "willow","WILLOWEEAGlobal": "willow","WILLOWRUGlobal": "willow","BILOBAGlobal": "biloba","BILOBAEEAGlobal": "biloba","BILOBARUGlobal": "biloba",
    "MERLIN": "merlin","MERLINTWGlobal": "merlin","MERLINGlobal": "merlin","MERLINEEAGlobal": "merlin","MERLINRUGlobal": "merlin","MERLININGlobal": "merlin","MERLINIDGlobal": "merlin","MERLINTRGlobal": "merlin","MERLINCLENGlobal": "merlin","MERLINMXTCGlobal": "merlin","MERLINMXATGlobal": "merlin","MERLINLMCRGlobal": "merlin",
    "LIME":"lime","LIMEPRE": "lime","LIMETWGlobal": "lime","LIMEGlobal": "lime","LIMEEEAGlobal": "lime","LIMERUGlobal": "lime","LIMEINGlobal": "lime","LIMEIDGlobal": "lime","LIMETRGlobal": "lime","LIMEMXTCGlobal": "lime","LIMELMCRGlobal": "lime",
    "CANNON":"cannon","CANNONPRE": "cannon","CANNONYUNKE": "cannon","CANNONGTWGlobal": "cannon","CANNONGGlobal": "cannon","CANNONGEEAGlobal": "cannon","CANNONGRUGlobal": "cannon","CANNONGTRGlobal": "cannon",
    "GAUGUIN":"gauguin","GAUGUINPRE": "gauguin","GAUGUINTWGlobal": "gauguin","GAUGUINGlobal": "gauguin","GAUGUINEEAGlobal": "gauguin","GAUGUININGlobal": "gauguin","GAUGUINTRGlobal": "gauguin",
    "JOYEUSETWGlobal": "joyeuse","JOYEUSEGlobal": "joyeuse","JOYEUSEEEAGlobal": "joyeuse","JOYEUSERUGlobal": "joyeuse","JOYEUSEIDGlobal": "joyeuse","JOYEUSETRGlobal": "joyeuse","JOYEUSECLENGlobal": "joyeuse",
    "EXCALIBURINGlobal": "excalibur",
    "CURTANAGlobal": "curtana","CURTANAEEAGlobal": "curtana","CURTANARUGlobal": "curtana","CURTANAINGlobal": "curtana","CURTANATRGlobal": "curtana","CURTANAMXATGlobal": "curtana",
    "MOJITOGlobal": "mojito","MOJITOEEAGlobal": "mojito","MOJITORUGlobal": "mojito","MOJITOINGlobal": "mojito","MOJITOIDGlobal": "mojito","MOJITOTRGlobal": "mojito",
    "CURTANAINRFGlobal": "curtana_in_rf",
    "SWEETTWGlobal": "sweet","SWEETGlobal": "sweet","SWEETEEAGlobal": "sweet","SWEETRUGlobal": "sweet","SWEETININGlobal": "sweet","SWEETIDGlobal": "sweet","SWEETTRGlobal": "sweet","SWEETCLENGlobal": "sweet","SWEETMXTCGlobal": "sweet","SWEETMXATGlobal": "sweet","SWEETLMCRGlobal": "sweet","SWEETZAVCGlobal": "sweet",
    "SWEETK6AGlobal":"sweet_k6a","SWEETK6AEEAGlobal":"sweet_k6a","SWEETK6ARUGlobal":"sweet_k6a",
    "CAMELLIA": "camellia","CAMELLIAPRE": "camellia","CAMELLIAEPSTDEE": "camellia","CAMELLIANTWGlobal": "camellia","CAMELLIANGlobal": "camellia","CAMELLIANEEAGlobal": "camellia","CAMELLIANRUGlobal": "camellia","CAMELLIAINGlobal": "camellia","CAMELLIANIDGlobal": "camellia","CAMELLIANTRGlobal": "camellia","CAMELLIANTHASGlobal": "camellia","CAMELLIANCLENGlobal": "camellia","CAMELLIANLMCRGlobal": "camellia","CAMELLIANMXATGlobal": "camellia",
    "CHOPIN": "chopin","CHOPINPRE": "chopin","CHOPINDEMO": "chopin","CHOPINEPKYWL": "chopin","CHOPINGlobal": "chopin","CHOPINIDGlobal": "chopin","CHOPINTRGlobal": "chopin",
    "LILACJPGlobal": "lilac",
    "SELENE": "selene","SELENES": "selene","SELENEEPTLY": "selene","SELENETWGlobal": "selene","SELENEGlobal": "selene","SELENEEEAGlobal": "selene","SELENERUGlobal": "selene","SELENEINGlobal": "selene","SELENEIDGlobal": "selene","SELENETRGlobal": "selene","SELENEMXATGlobal": "selene","SELENELMCRGlobal": "selene",
    "EVERGO": "evergo","EVERGOPRE": "evergo","EVERGOEPCQRCB": "evergo","EVERGOEPEC": "evergo","EVERGOEPSTDEE": "evergo","EVERGOEPSXHT": "evergo","EVERGOEPYFAN": "evergo","EVERGOEPYX": "evergo","EVERGOINGlobal": "evergo",
    "PISSARRO": "pissarro", "PISSARROPRE":"pissarro","PISSARROTWGlobal": "pissarro","PISSARROGlobal": "pissarro","PISSARROEEAGlobal": "pissarro","PISSARRORUGlobal": "pissarro","PISSARROTRGlobal": "pissarro",
    "SPESGlobal": "spes","SPESINGlobal": "spes","SPESTRGlobal": "spes","SPESCLENGlobal": "spes","SPESMXATGlobal": "spes","SPESLMCRGlobal": "spes","SPESLMMSGlobal": "spes","SPESNGlobal": "spesn","SPESNEEAGlobal": "spesn","SPESNRUGlobal": "spesn","SPESNIDGlobal": "spesn","SPESNZAMTGlobal": "spesn",
    "VEUX": "veux","VEUXEPSTDEE": "veux","VEUXTWGlobal": "veux","VEUXGlobal": "veux","VEUXEEAGlobal": "veux","VEUXRUGlobal": "veux","VEUXINGlobal": "veux","VEUXIDGlobal": "veux","VEUXTRGlobal": "veux","VEUXJPGlobal": "veux","VEUXCLENGlobal": "veux","VEUXLMCRGlobal": "veux","VEUXMXATGlobal": "veux",
    "FLEURTWGlobal": "fleur","FLEURGlobal": "fleur","FLEUREEAGlobal": "fleur","FLEURRUGlobal": "fleur","FLEURINGlobal": "fleur","FLEURIDGlobal": "fleur","FLEURTRGlobal": "fleur","FLEURCLENGlobal": "fleur","FLEURLMCRGlobal": "fleur","FLEURMXATGlobal": "fleur","FLEURLMMSGlobal": "fleur",
    "VIVATWGlobal": "viva","VIVAGlobal": "viva","VIVAEEAGlobal": "viva","VIVARUGlobal": "viva","VIVAIDGlobal": "viva","VIVATRGlobal": "viva","VIVALMCRGlobal": "viva","VIVALMMSGlobal": "viva","VIVAZAMTGlobal": "viva","VIDAINGlobal": "vida",
    "LIGHT": "light","LIGHTEPSTDCE": "light","LIGHTEPXY": "light","LIGHTEPXDJA": "light","LIGHTEPSTDEE": "light","LIGHTTWGlobal": "light","LIGHTGlobal": "light","LIGHTEEAGlobal": "light","LIGHTRUGlobal": "light","LIGHTINGlobal": "light","LIGHTIDGlobal": "light","LIGHTTRGlobal": "light","LIGHTTHASGlobal": "light","LIGHTCLENGlobal": "light","LIGHTLMCRGlobal": "light",
    "LIGHTCM":"lightcm","LIGHTCMEPSTDEE":"lightcm",
    "OPALTWGlobal": "opal","OPALGlobal": "opal","OPALEEAGlobal": "opal","OPALRUGlobal": "opal","OPALCLENGlobal": "opal","OPALMXATGlobal": "opal","OPALLMCRGlobal": "opal",
    "XAGA": "xaga","XAGATWGlobal": "xaga","XAGAGlobal": "xaga","XAGAEEAGlobal": "xaga","XAGARUGlobal": "xaga","XAGAINGlobal": "xaga","XAGATRGlobal": "xaga",
    "SUNSTONE": "sunstone","SUNSTONEEPSTDEE": "sunstone","SUNSTONEINGlobal": "sunstone","SUNSTONEGlobal":"sunstone","SUNSTONEEEAGlobal":"sunstone",
    "RUBY": "ruby","RUBYEPSTDEE": "ruby","RUBYINGlobal": "ruby","RUBYGlobal":"ruby","RUBYIDGlobal":"ruby","RUBYTWGlobal":"ruby","RUBYEEAGlobal":"ruby",
    "REDWOOD": "redwood","REDWOODTWGlobal": "redwood","REDWOODGlobal": "redwood","REDWOODEEAGlobal": "redwood","REDWOODRUGlobal": "redwood","REDWOODINGlobal": "redwood","REDWOODTRGlobal": "redwood",
    "DAVINCI": "davinci","DAVINCIGlobal": "davinci","DAVINCIEEAGlobal": "davinci","DAVINCIRUGlobal": "davinci","DAVINCIININGlobal": "davinci",
    "RAPHAEL": "raphael","RAPHAELGlobal": "raphael","RAPHAELEEAGlobal": "raphael","RAPHAELRUGlobal": "raphael","RAPHAELININGlobal": "raphael",
    "RAPHAELS": "raphaels",
    "PHOENIX": "phoenix","PHOENIXPRE": "phoenix","PHOENIXININGlobal": "phoenix",
    "PICASSO": "picasso","PICASSOPRE": "picasso",
    "PICASSO48M": "picasso_48m","PICASSO48MPRE": "picasso_48m",
    "LMI": "lmi","LMIPRE": "lmi","LMIGlobal": "lmi","LMIEEAGlobal": "lmi","LMIRUGlobal": "lmi","LMIIDGlobal": "lmi","LMITRGlobal": "lmi",
    "CEZANNE":"cezanne","CEZANNEPRE": "cezanne",
    "APOLLO":"apollo","APOLLOPRE": "apollo","APOLLOTWGlobal": "apollo","APOLLOGlobal": "apollo","APOLLOEEAGlobal": "apollo","APOLLORUGlobal": "apollo","APOLLOINGlobal": "apollo","APOLLOIDGlobal": "apollo","APOLLOTRGlobal": "apollo","APOLLOCLENGlobal": "apollo",
    "ALIOTH": "alioth","ALIOTHPRE": "alioth","ALIOTHEPYUNKE": "alioth","ALIOTHTWGlobal": "alioth","ALIOTHGlobal": "alioth","ALIOTHEEAGlobal": "alioth","ALIOTHRUGlobal": "alioth","ALIOTHINGlobal": "alioth","ALIOTHIDGlobal": "alioth","ALIOTHTRGlobal": "alioth",
    "ARES": "ares","ARESPRE": "ares","ARESINGlobal": "ares",
    "MUNCH": "munch","MUNCHTWGlobal": "munch","MUNCHGlobal": "munch","MUNCHEEAGlobal": "munch","MUNCHRUGlobal": "munch","MUNCHINGlobal": "munch","MUNCHIDGlobal": "munch","MUNCHTRGlobal": "munch",
    "INGRES": "ingres","INGRESTWGlobal": "ingres","INGRESGlobal": "ingres","INGRESEEAGlobal": "ingres","INGRESRUGlobal": "ingres","INGRESIDGlobal": "ingres","INGRESTRGlobal": "ingres",
    "RUBENS": "rubens","RUBENSEPSTDEE": "rubens","RUBENSDEMO":"rubens",
    "MATISSE": "matisse","MATISSEEPSTDEE": "matisse",
    "DITING": "diting","DITINGTWGlobal": "diting","DITINGGlobal": "diting","DITINGEEAGlobal": "diting","DITINGRUGlobal": "diting","DITINGTRGlobal": "diting","DITINGCLENGlobal": "diting","DITINGLMCRGlobal": "diting","DITINGMXATGlobal": "diting","DITINGJPGlobal": "diting","DITINGEPSTDEE":"diting",
    "MONDRIAN": "mondrian","MONDRIANEPSTDEE":"mondrian",
    "SOCRATES": "socrates",
    "REMBRANDT": "rembrandt",
    "YUNLUO": "yunluo","YUNLUOTWGlobal": "yunluo","YUNLUOGlobal": "yunluo","YUNLUOEEAGlobal": "yunluo","YUNLUORUGlobal": "yunluo","YUNLUOINGlobal": "yunluo","YUNLUOIDGlobal": "yunluo","YUNLUOTRGlobal": "yunluo",
    "HMPro": "omega","OMEGA": "omega",
    "HMS2": "ysl","YSL": "ysl","HMS2Global": "ysl","HMS2RUGlobal": "ysl","HMS2CLMOVIESTARGlobal": "ysl",
    "TIAREGlobal": "tiare","TIAREEEAGlobal": "tiare","TIARERUGlobal": "tiare","TIAREINGlobal": "tiare",
    "ONCINGlobal": "onc",
    "ICETWGlobal": "ice","ICEGlobal": "ice","ICEEEAGlobal": "ice","ICERUGlobal": "ice","ICEINGlobal": "ice","ICEIDGlobal": "ice",
    "ANGELICAININRFGlobal": "angelicain",
    "FROSTTWGlobal": "frost","FROSTGlobal": "frost","FROSTEEAGlobal": "frost","FROSTRUGlobal": "frost","FROSTIDGlobal": "frost",
    "POCOF1Global": "beryllium","BERYLLIUMGlobal": "beryllium","POCOF1RUGlobal": "beryllium","BERYLLIUMRUGlobal": "beryllium",
    "SHIVAINGlobal": "shiva",
    "GRAMINGlobal": "gram",
    "CITRUSTWGlobal": "citrus","CITRUSGlobal": "citrus","CITRUSEEAGlobal": "citrus","CITRUSRUGlobal": "citrus","CITRUSINGlobal": "citrus","CITRUSIDGlobal": "citrus","CITRUSTRGlobal": "citrus",
    "ROCKTWGlobal": "rock","ROCKGlobal": "rock","ROCKEEAGlobal": "rock","ROCKRUGlobal": "rock","ROCKINGlobal": "rock","ROCKIDGlobal": "rock","ROCKTRGlobal": "rock",
    "ROSEMARYPTWGlobal": "rosemary_p","ROSEMARYPGlobal": "rosemary_p","ROSEMARYPEEAGlobal": "rosemary_p","ROSEMARYPRUGlobal": "rosemary_p","ROSEMARYPIDGlobal": "rosemary_p","ROSEMARYPTRGlobal": "rosemary_p",
    "SURYAGlobal": "surya","SURYAEEAGlobal": "surya","SURYARUGlobal": "surya","SURYAINGlobal": "surya","SURYAIDGlobal": "surya","SURYATRGlobal": "surya",
    "VAYUTWGlobal": "vayu","VAYUGlobal": "vayu","VAYUEEAGlobal": "vayu","VAYURUGlobal": "vayu","VAYUINGlobal": "vayu","VAYUIDGlobal": "vayu","VAYUTRGlobal": "vayu",
    "MOONSTONETWGlobal": "moonstone","MOONSTONEGlobal": "moonstone","MOONSTONEEEAGlobal": "moonstone","MOONSTONERUGlobal": "moonstone","MOONSTONEINGlobal":"moonstone","MOONSTONEIDGlobal":"moonstone",
    "EARTH":"earth","EARTHINGlobal":"earth","EARTHCLENGlobal":"earth","EARTHGlobal":"earth","EARTHIDGlobal":"earth","EARTHLMCRGlobal":"earth","EARTHTRGlobal":"earth","EARTHEEAGlobal":"earth","EARTHEPSTDEE":"earth","EARTHTWGlobal":"earth",
    "ROSEMARYGlobal":"rosemary","ROSEMARYLMCRGlobal":"rosemary","ROSEMARYCLENGlobal":"rosemary","ROSEMARYIDGlobal":"rosemary","ROSEMARYMXATGlobal":"rosemary","ROSEMARYMXTCGlobal":"rosemary","ROSEMARYRUGlobal":"rosemary","ROSEMARYTRGlobal":"rosemary","ROSEMARYTWGlobal":"rosemary","ROSEMARYZAMTGlobal":"rosemary","ROSEMARYZAVCGlobal":"rosemary",
    "EVERGREENGlobal":"evergreen","EVERGREENRUGlobal":"evergreen","EVERGREENTRGlobal":"evergreen","EVERGREENTWGlobal":"evergreen",
    "TAPASGlobal":"tapas","TAPASINGlobal":"tapas","TAPASTRGlobal":"tapas",
    "TOPAZEEAGlobal":"topaz","TOPAZGlobal":"topaz","TOPAZIDGlobal":"topaz","TOPAZTRGlobal":"topaz",
    "WATEREEAGlobal":"water","WATERGlobal":"water","WATERIDGlobal":"water","WATERINGlobal":"water","WATERTWGlobal":"water",
    "ISHTAR":"ishtar","ISHTARGlobal":"ishtar","ISHTARRUGlobal":"ishtar","ISHTARTWGlobal":"ishtar",
    "PIPA":"pipa","PIPAEEAGlobal":"pipa","PIPAGlobal":"pipa","PIPAIDGlobal":"pipa","PIPAINGlobal":"pipa","PIPARUGlobal":"pipa","PIPATRGlobal":"pipa","PIPATWGlobal":"pipa",
    "LIUQIN":"liuqin",
    "MARBLE":"marble","MARBLEEEAGlobal":"marble","MARBLEGlobal":"marble","MARBLEINGlobal":"marble","MARBLEIDGlobal":"marble","MARBLERUGlobal":"marble","MARBLETRGlobal":"marble","MARBLETWGlobal":"marble",
    "MONETEEAHGGlobal": "monet","MONETEEAORGlobal": "monet","MONETEEATFGlobal": "monet","MONETEEAVFGlobal": "monet","MONETEEASFGlobal": "monet","MONETEEATIGlobal": "monet",
    "RENOIREEAHGGlobal": "renoir","RENOIREEAORGlobal": "renoir","RENOIREEATFGlobal": "renoir","RENOIREEAVFGlobal": "renoir",
    "AGATEEEAHGGlobal": "agate","AGATEEEAORGlobal": "agate","AGATEEEATFGlobal": "agate","AGATEEEABYGlobal": "agate","AGATEEEAVFGlobal": "agate","AGATEEEASFGlobal": "agate","AGATEEEATIGlobal": "agate",
    "LISAEEAHGGlobal": "lisa","LISAEEAORGlobal": "lisa","LISAEEATFGlobal": "lisa","LISAEEABYGlobal": "lisa","LISAEEAVFGlobal": "lisa","LISAEEASFGlobal": "lisa","LISAEEATIGlobal": "lisa",
    "MERLINEEAHGGlobal": "merlin",
    "MERLINEEAORGlobal": "merlin",
    "MERLINEEATFGlobal": "merlin",
    "MERLINEEAVFGlobal": "merlin",
    "MERLINEEASFGlobal": "merlin","MERLINEEATIGlobal": "merlin",
    "LANCELOTEEAHGGlobal": "lancelot",
    "LANCELOTEEAORGlobal": "lancelot",
    "FIREINGlobal": "fire",
    "FIRETRGlobal": "fire",
    "SKYEEAGlobal": "sky",
    "LANCELOTEEATFGlobal": "lancelot",
    "LANCELOTEEAVFGlobal": "lancelot",
    "DANDELIONEEATFGlobal": "dandelion",
    "DANDELIONEEAVFGlobal": "dandelion",
    "DANDELIONEEASFGlobal": "dandelion",
    "DANDELIONEEATIGlobal": "dandelion",
    "ANGELICANEEAORGlobal": "angelican",
    "EARTHRUGlobal": "earth",
    "ROSEMARYEEAGlobal": "rosemary",
    "ROSEMARYINGlobal": "rosemary",
    "EVERGOEPYUNKE": "evergo",
    "RUBYTRGlobal": "ruby",
    "MARBLEDEMO": "marble",
    "TOPAZRUGlobal": "topaz",
    "EVERGREENEEAGlobal": "evergreen",
    "RENOIREEASFGlobal": "renoir",
    "RENOIREEATIGlobal": "renoir",
    "SELENEEEAHGGlobal": "selene",
    "SELENEEEAORGlobal": "selene",
    "SELENEEEATFGlobal": "selene",
    "SELENEEEABYGlobal": "selene",
    "SELENEEEAVFGlobal": "selene",
    "SELENEEEASFGlobal": "selene",
    "UMIEEAHGGlobal": "umi",
    "UMIEEAORGlobal": "umi",
    "UMIEEATFGlobal": "umi",
    "UMIEEAVFGlobal": "umi",
    "UMIEEASFGlobal": "umi",
    "UMIEEATIGlobal": "umi",
    "VENUSEEAHGGlobal": "venus",
    "VENUSEEAORGlobal": "venus",
    "VENUSEEATFGlobal": "venus",
    "VENUSEEAVFGlobal": "venus",
    "VENUSEEASFGlobal": "venus",
    "VENUSEEATIGlobal": "venus",
    "STAREEAORGlobal": "star",
    "STAREEAVFGlobal": "star",
    "VILIEEAORGlobal": "vili",
    "VILIEEATFGlobal": "vili",
    "VILIEEAVFGlobal": "vili",
    "VILIEEASFGlobal": "vili",
    "TOCOEEAORGlobal": "toco",
    "TOCOEEATFGlobal": "toco",
    "TOCOEEAVFGlobal": "toco",
    "SUNSTONETWGlobal": "sunstone",
    "RUBYRUGlobal": "ruby",
    "ISHTAREEAGlobal": "ishtar",
    "SEAGlobal": "sea",
    "SEAEEAGlobal": "sea",
    "SEARUGlobal": "sea",
    "SEATRGlobal": "sea",
    "MONDRIANTWGlobal": "mondrian",
    "MONDRIANEEAGlobal": "mondrian",
    "MONDRIANRUGlobal": "mondrian",
    "MONDRIANTRGlobal": "mondrian",
    "SUNSTONEDEMO":"sunstone","SUNSTONEEPTKGWDL":"sunstone",
    "ISHTARDEMO":"ishtar",
    "MONDRIANGlobal":"mondrian",
    "YUECHU":"yuechu",
    "CAMELLIAEPYUNKE":"camellia",
    "PEARL":"pearl",
    "MOONSTONETRGlobal":"moonstone",
    "PSYCHEEPSTDEE":"psyche",
    "UNICORNDEMO": "unicorn",
    "ZIYIDEMO": "ziyi",
    "REDWOODIDGlobal": "redwood",
    "SWEETK6ATRGlobal": "sweet_k6a",
    "SEATWGlobal": "sea",
    "FIREGlobal":"fire",
    "FIREEEAGlobal":"fire",
    "FIRERUGlobal":"fire",
    "RUBENSEPYX":"rubens",
    "PISSARROEPYUNKE":"pissarro",
    "CAMELLIAEPYX":"camellia",
    "SOCRATESEPSTDEE":"socrates",
    "NUWAEPSDLYBJCG":"nuwa",
    "SKY":"sky",
    "SKYINGlobal":"sky",
    "ENUMAEPSTDEE":"enuma",
    "RUBYKRGlobal":"ruby",
    "SWEETK6AIDGlobal":"sweet_k6a",
    "WATERRUGlobal":"water",
    "FROSTTRGlobal":"frost",
    "UNICORNEPSTDEE":"unicorn",
    "COROTDEMO":"corot",
    "COROT":"corot",
    "YUDI":"yudi",
    "YUDIDEMO":"yudi",
    "YUNLUOEPSTDEE":"yunluo",
    "BABYLON":"babylon",
    "BABYLONDEMO":"babylon",
    "XUNTWGlobal":"xun",
    "XUNGlobal":"xun",
    "XUNEEAGlobal":"xun",
    "SKYTWGlobal":"sky"
    }


def localData(codename):
      if platform == "win32":
        devdata = json.loads(open("static/data/data/devices/"+codename+".json", 'r', encoding='utf-8').read()).__str__()
      else:
        devdata = json.loads(open("/sdcard/Codes/NuxtMR/static/data/data/devices/"+codename+".json", 'r', encoding='utf-8').read()).__str__()
      return devdata

def writeData(filename):
  print("发现未收录版本")
  if platform == "win32":
    file = open("static/data/scripts/NewROMs.txt", "a", encoding='utf-8')
  else:
    file = open("/sdcard/Codes/NuxtMR/static/data/script/NewROMs.txt", "a", encoding='utf-8')
  file.write(filename+"\n")
  file.close()

def getDeviceCode(filename):
  if ".zip" in filename:
    flag = filename.split('_')[1]
    codename = flags[flag]
    return codename
  elif ".tgz" in filename:
    if "_c3l2_" in filename:
      codename = "dandelion_c3l2"
    elif "_k6a_" in filename:
      codename = "sweet_k6a"
    else:
      codename = filename.split('_')[0]
      if codename == "sweetin":
        codename = "sweet"
      elif codename == "an":
    return codename
def checkExit(filename):
  if "blockota" in filename:
    i = 0
  else:
    if filename in localData(getDeviceCode(filename)):
      i = 0
    else:
      writeData(filename)
